# process_raw.ipynb

This notebook reads in the raw ACS PUMA data and performs cleaning on it to serve as final refdata for PUMA statistics. It also performs aggregation on the PUMA data to get statistics for MIGPUMAs.

In [24]:
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.abspath("../.."))
from lib import io as lio

In [25]:
one_year_acs = "R50171584_SL795.csv"
five_year_acs = "R50171626_SL795.csv"
table_csv = "acs_tables_2018.txt"
year = 2018

In [26]:
acs1_code_to_name = pd.read_fwf(
    "./raw/" + table_csv, colspecs=[(0, 8), (8, None)]
).set_index("Table")
acs1_code_to_name

                                                     Title
Table
A00001                                    Total Population
A00002                   Population Density (Per Sq. Mile)
A00003                               Land Area (Sq. Miles)
A02001                                                 Sex
A02002                                          Sex by Age
...                                                    ...
A20002                             Health Insurance by Age
A10048       Occupied Housing Units by Complete Facilities
A10033B  Complete Facilities (Renter-Occupied Housing U...
A10029   Housing Units by Telephone Service Available b...
A10061B  Telephone Service Available (Renter-Occupied H...

[221 rows x 1 columns]

In [27]:
acs1_df = pd.read_csv("./raw/" + one_year_acs, header=[0, 1], index_col=0)
acs1_df.columns = [
    ".".join(str(level.replace(":", "")) for level in col) for col in acs1_df.columns
]
acs1_df.index = acs1_df.index.astype(str).str.zfill(7)
acs1_df.index.name = "PUMA"
acs1_df = acs1_df[
    ~acs1_df["State/U.S.-Abbreviation (USPS).Geo_STUSAB"].isin(["ak", "hi", "pr"])
]
acs1_df.head()

,Geographic Identifier.Geo_GEOID,Name of Area.Geo_NAME,Qualifying Name.Geo_QName,State/U.S.-Abbreviation (USPS).Geo_STUSAB,Summary Level.Geo_SUMLEV,Geographic GEOCOMP.Geo_GEOCOMP,File Identification.Geo_FILEID,Logical Record Number.Geo_LOGRECNO,US.Geo_US,Region.Geo_REGION,...,Occupied Housing Units with Telephone Service Available Householder 15 to 34 Years.SE_A10029_003,Occupied Housing Units with Telephone Service Available Householder 35 to 64 Years.SE_A10029_004,Occupied Housing Units with Telephone Service Available Householder 65 Years and Over.SE_A10029_005,Occupied Housing Units No Telephone Service Available.SE_A10029_006,Occupied Housing Units No Telephone Service Available Householder 15 to 34 Years.SE_A10029_007,Occupied Housing Units No Telephone Service Available Householder 35 to 64 Years.SE_A10029_008,Occupied Housing Units No Telephone Service Available Householder 65 Years and Over.SE_A10029_009,Renter-Occupied Housing Units.SE_A10061B_001,Renter-Occupied Housing Units with Telephone Service Available.SE_A10061B_002,Renter-Occupied Housing Units No Telephone Service Available.SE_A10061B_003
PUMA,,,,,,,,,,,,,,,,,,,,,
0100100,79500US0100100,"Lauderdale, Colbert, Franklin & Marion (Northe...","Lauderdale, Alabama",al,795,0,ACSSF,57,NaN,NaN,...,12763.0,34075.0,23005.0,3888.0,987.0,2198.0,703.0,23052.0,20665.0,2387.0
0100200,79500US0100200,Limestone & Madison (Outer) Counties--Huntsvil...,Limestone & Madison (Outer) Counties--Huntsvil...,al,795,0,ACSSF,58,NaN,NaN,...,12596.0,42233.0,16872.0,759.0,0.0,601.0,158.0,16978.0,16355.0,623.0
0100301,79500US0100301,Huntsville (North) & Madison (East) Cities PUM...,Huntsville (North) & Madison (East) Cities PUM...,al,795,0,ACSSF,59,NaN,NaN,...,13001.0,30361.0,12674.0,701.0,148.0,191.0,362.0,22396.0,22036.0,360.0
0100302,79500US0100302,"Huntsville City (Central & South) PUMA, Alabama","Huntsville City (Central & South) PUMA, Alabama",al,795,0,ACSSF,60,NaN,NaN,...,9463.0,22143.0,11687.0,583.0,121.0,350.0,112.0,18503.0,18079.0,424.0
0100400,79500US0100400,"DeKalb & Jackson Counties PUMA, Alabama","DeKalb & Jackson Counties PUMA, Alabama",al,795,0,ACSSF,61,NaN,NaN,...,7812.0,24853.0,13875.0,609.0,214.0,309.0,86.0,12206.0,12053.0,153.0

In [28]:
# lower 48 + dc
print(acs1_df["State/U.S.-Abbreviation (USPS).Geo_STUSAB"].nunique())

49

In [29]:
print(acs1_df.index.is_unique, acs1_df.columns.is_unique)

True True

In [30]:
acs5_df = pd.read_csv("./raw/" + five_year_acs, header=[0, 1], index_col=0)
acs5_df.columns = [
    ".".join(str(level.replace(":", "")) for level in col) for col in acs5_df.columns
]
acs5_df.index = acs5_df.index.astype(str).str.zfill(7)
acs5_df.index.name = "PUMA"
acs5_df = acs5_df[
    ~acs5_df["State/U.S.-Abbreviation (USPS).Geo_STUSAB"]
    .str.lower()
    .isin(["ak", "hi", "pr"])
]
acs5_df.head()

,Name of Area.Geo_NAME,Qualified Area Name.Geo_qname,State/U.S.-Abbreviation (USPS).Geo_STUSAB,Summary Level.Geo_SUMLEV,Geographic Component.Geo_GEOCOMP,File Identification.Geo_FILEID,Logical Record Number.Geo_LOGRECNO,US.Geo_US,Region.Geo_REGION,Division.Geo_DIVISION,...,Own Children under 18 Years.SE_A10065_001,Own Children under 18 Years Children Living with Single Parents.SE_A10065_002,Households.SE_A10066_001,Households 1-Person Household.SE_A10066_002,Households 2-Person Household.SE_A10066_003,Households 3-Person Household.SE_A10066_004,Households 4-Person Household.SE_A10066_005,Households 5-Person Household.SE_A10066_006,Households 6-Person Household.SE_A10066_007,Households 7-or-More Person Household.SE_A10066_008
PUMA,,,,,,,,,,,,,,,,,,,,,
0100100,Lauderdale,"Lauderdale, Colbert, Franklin & Marion (Northe...",AL,795,0,ACSSF,8665,NaN,NaN,NaN,...,34024,10838,74643,21789,28179,11226,8359,3640,920,530
0100200,Limestone & Madison (Outer) Counties--Huntsvil...,Limestone & Madison (Outer) Counties--Huntsvil...,AL,795,0,ACSSF,8666,NaN,NaN,NaN,...,39583,8678,69828,16998,25155,11558,10273,4187,1240,417
0100301,Huntsville (North) & Madison (East) Cities PUMA,Huntsville (North) & Madison (East) Cities PUM...,AL,795,0,ACSSF,8667,NaN,NaN,NaN,...,24780,7219,52260,17199,16648,8358,6166,2525,984,380
0100302,Huntsville City (Central & South) PUMA,"Huntsville City (Central & South) PUMA, Alabama",AL,795,0,ACSSF,8668,NaN,NaN,NaN,...,18991,7424,43997,16156,15219,5878,4280,1693,520,251
0100400,DeKalb & Jackson Counties PUMA,"DeKalb & Jackson Counties PUMA, Alabama",AL,795,0,ACSSF,8669,NaN,NaN,NaN,...,24070,7277,46758,12733,16828,7197,5944,2653,809,594

In [31]:
# lower 48 + dc
print(acs5_df["State/U.S.-Abbreviation (USPS).Geo_STUSAB"].nunique())

49

In [32]:
print(acs5_df.index.is_unique, acs5_df.columns.is_unique)

True True

In [33]:
# compare puma differences between 1-year and 5-year ACS data
# for cross-decade migration analysis, the PUMA definitions may change
print(set(acs5_df.index).symmetric_difference(set(acs1_df.index)))

set()

In [34]:
# use the 5-year ACS data to fill in missing data in the 1-year ACS data
# the 1-year ACS data has a lot more nas since for small populations, data is ommitted due to small sample sizes

# create a dictionary to rename the columns in the 5-year ACS data to match the 1-year ACS data using the underlying codes which should be constant
acs1_df_se_code_to_col = dict()
for col in acs1_df.columns:
    segments = col.split(".")
    se_code = segments[-1]
    desc = "".join(segments[:-1])
    acs1_df_se_code_to_col[se_code] = (col, desc)


rename_map = {}
no_match = []
for col in acs5_df.columns:
    segments = col.split(".")
    acs5_se_code = segments[-1]
    acs5_desc = "".join(segments[:-1])
    # do not rename geo columns, do not care about these
    if "Geo" in acs5_se_code:
        continue

    match_found = False
    for se_code, (acs1_col, asc1_desc) in acs1_df_se_code_to_col.items():
        if se_code == acs5_se_code:
            # NOTE: the descriptions can be off, but that is likely due to social explorer just naming things differently
            # a cursory search showed that the description differences don't mean anything
            print(f"{acs5_desc} -> {asc1_desc}")
            rename_map[col] = acs1_col
            match_found = True
            break  # stop at first match to avoid overwriting on multiple hits

    if not match_found:
        no_match.append(col)

print()
for col in no_match:
    print(col)

# only keep the columns in the 5-year ACS data that have a match in the 1-year ACS data
acs5_df_cleaned = acs5_df.rename(columns=rename_map)
acs1_df_cols = set(acs1_df.columns)
acs5_df_cleaned = acs5_df_cleaned[
    [col for col in acs5_df_cleaned.columns if col in acs1_df_cols]
]

Total Population -> Total Population
Total Population -> Total Population
Population Density (Per Sq Mile) -> Population Density (Per Sq Mile)
Area (Land) -> Area (Land)
Area Total -> Area Total
Area Total Area (Land) -> Area Total Area (Land)
Area Total Area (Water) -> Area Total Area (Water)
Total Population -> Total Population
Total Population Male -> Total Population Male
Total Population Female -> Total Population Female
Total Population -> Total Population
Total Population Male -> Total Population Male
Total Population Male Under 5 Years -> Total Population Male Under 5 Years
Total Population Male 5 to 9 Years -> Total Population Male 5 to 9 Years
Total Population Male 10 to 14 Years -> Total Population Male 10 to 14 Years
Total Population Male 15 to 17 Years -> Total Population Male 15 to 17 Years
Total Population Male 18 to 24 Years -> Total Population Male 18 to 24 Years
Total Population Male 25 to 34 Years -> Total Population Male 25 to 34 Years
Total Population Male 35 to 44 Years -> Total Population Male 35 to 44 Years
Total Population Male 45 to 54 Years -> Total Population Male 45 to 54 Years
Total Population Male 55 to 64 Years -> Total Population Male 55 to 64 Years
Total Population Male 65 to 74 Years -> Total Population Male 65 to 74 Years
Total Population Male 75 to 84 Years -> Total Population Male 75 to 84 Years
Total Population Male 85 Years and Over -> Total Population Male 85 Years and Over
Total Population Female -> Total Population Female
Total Population Female Under 5 Years -> Total Population Female Under 5 Years
Total Population Female 5 to 9 Years -> Total Population Female 5 to 9 Years
Total Population Female 10 to 14 Years -> Total Population Female 10 to 14 Years
Total Population Female 15 to 17 Years -> Total Population Female 15 to 17 Years
Total Population Female 18 to 24 Years -> Total Population Female 18 to 24 Years
Total Population Female 25 to 34 Years -> Total Population Female 25 to 34 Years
Total Population Female 35 to 44 Years -> Total Population Female 35 to 44 Years
Total Population Female 45 to 54 Years -> Total Population Female 45 to 54 Years
Total Population Female 55 to 64 Years -> Total Population Female 55 to 64 Years
Total Population Female 65 to 74 Years -> Total Population Female 65 to 74 Years
Total Population Female 75 to 84 Years -> Total Population Female 75 to 84 Years
Total Population Female 85 Years and Over -> Total Population Female 85 Years and Over
Total Population -> Total Population
Total Population Male -> Total Population Male
Total Population Male Less than 5 Years -> Total Population Male Less than 5 Years
Total Population Male Less than 10 Years -> Total Population Male Less than 10 Years
Total Population Male Less than 15 Years -> Total Population Male Less than 15 Years
Total Population Male Less than 18 Years -> Total Population Male Less than 18 Years
Total Population Male Less than 25 Years -> Total Population Male Less than 25 Years
Total Population Male Less than 35 Years -> Total Population Male Less than 35 Years
Total Population Male Less than 45 Years -> Total Population Male Less than 45 Years
Total Population Male Less than 55 Years -> Total Population Male Less than 55 Years
Total Population Male Less than 65 Years -> Total Population Male Less than 65 Years
Total Population Male Less than 75 Years -> Total Population Male Less than 75 Years
Total Population Male Less than 85 Years -> Total Population Male Less than 85 Years
Total Population Female -> Total Population Female
Total Population Female Less than 5 Years -> Total Population Female Less than 5 Years
Total Population Female Less than 10 Years -> Total Population Female Less than 10 Years
Total Population Female Less than 15 Years -> Total Population Female Less than 15 Years
Total Population Female Less than 18 Years -> Total Population Female Less than 18 Years
Total Population Female Less than 25 Years -> Total Population Female Less than 25 Years
Total Population Female Less than 35 Years -> Total Population Female Less than 35 Years
Total Population Female Less than 45 Years -> Total Population Female Less than 45 Years
Total Population Female Less than 55 Years -> Total Population Female Less than 55 Years
Total Population Female Less than 65 Years -> Total Population Female Less than 65 Years
Total Population Female Less than 75 Years -> Total Population Female Less than 75 Years
Total Population Female Less than 85 Years -> Total Population Female Less than 85 Years
Total Population -> Total Population
Total Population Male -> Total Population Male
Total Population Male More than 5 Years -> Total Population Male More than 5 Years
Total Population Male More than 10 Years -> Total Population Male More than 10 Years
Total Population Male More than 15 Years -> Total Population Male More than 15 Years
Total Population Male More than 18 Years -> Total Population Male More than 18 Years
Total Population Male More than 25 Years -> Total Population Male More than 25 Years
Total Population Male More than 35 Years -> Total Population Male More than 35 Years
Total Population Male More than 45 Years -> Total Population Male More than 45 Years
Total Population Male More than 55 Years -> Total Population Male More than 55 Years
Total Population Male More than 65 Years -> Total Population Male More than 65 Years
Total Population Male More than 75 Years -> Total Population Male More than 75 Years
Total Population Male More than 85 Years -> Total Population Male More than 85 Years
Total Population Female -> Total Population Female
Total Population Female More than 5 Years -> Total Population Female More than 5 Years
Total Population Female More than 10 Years -> Total Population Female More than 10 Years
Total Population Female More than 15 Years -> Total Population Female More than 15 Years
Total Population Female More than 18 Years -> Total Population Female More than 18 Years
Total Population Female More than 25 Years -> Total Population Female More than 25 Years
Total Population Female More than 35 Years -> Total Population Female More than 35 Years
Total Population Female More than 45 Years -> Total Population Female More than 45 Years
Total Population Female More than 55 Years -> Total Population Female More than 55 Years
Total Population Female More than 65 Years -> Total Population Female More than 65 Years
Total Population Female More than 75 Years -> Total Population Female More than 75 Years
Total Population Female More than 85 Years -> Total Population Female More than 85 Years
Total Population -> Total Population
Total Population Male -> Total Population Male
Total Population Male Under 18 Years -> Total Population Male Under 18 Years
Total Population Male 18 to 34 Years -> Total Population Male 18 to 34 Years
Total Population Male 35 to 64 Years -> Total Population Male 35 to 64 Years
Total Population Male 65 Years and Over -> Total Population Male 65 Years and Over
Total Population Female -> Total Population Female
Total Population Female Under 18 Years -> Total Population Female Under 18 Years
Total Population Female 18 to 34 Years -> Total Population Female 18 to 34 Years
Total Population Female 35 to 64 Years -> Total Population Female 35 to 64 Years
Total Population Female 65 Years and Over -> Total Population Female 65 Years and Over
Total Population -> Total Population
Total Population Under 5 Years -> Total Population Under 5 Years
Total Population 5 to 9 Years -> Total Population 5 to 9 Years
Total Population 10 to 14 Years -> Total Population 10 to 14 Years
Total Population 15 to 17 Years -> Total Population 15 to 17 Years
Total Population 18 to 24 Years -> Total Population 18 to 24 Years
Total Population 25 to 34 Years -> Total Population 25 to 34 Years
Total Population 35 to 44 Years -> Total Population 35 to 44 Years
Total Population 45 to 54 Years -> Total Population 45 to 54 Years
Total Population 55 to 64 Years -> Total Population 55 to 64 Years
Total Population 65 to 74 Years -> Total Population 65 to 74 Years
Total Population 75 to 84 Years -> Total Population 75 to 84 Years
Total Population 85 Years and Over -> Total Population 85 Years and Over
Total Population -> Total Population
Total Population Less than 5 Years -> Total Population Less than 5 Years
Total Population Less than 10 Years -> Total Population Less than 10 Years
Total Population Less than 15 Years -> Total Population Less than 15 Years
Total Population Less than 18 Years -> Total Population Less than 18 Years
Total Population Less than 25 Years -> Total Population Less than 25 Years
Total Population Less than 35 Years -> Total Population Less than 35 Years
Total Population Less than 45 Years -> Total Population Less than 45 Years
Total Population Less than 55 Years -> Total Population Less than 55 Years
Total Population Less than 65 Years -> Total Population Less than 65 Years
Total Population Less than 75 Years -> Total Population Less than 75 Years
Total Population Less than 85 Years -> Total Population Less than 85 Years
Total Population -> Total Population
Total Population More than 5 Years -> Total Population More than 5 Years
Total Population More than 10 Years -> Total Population More than 10 Years
Total Population More than 15 Years -> Total Population More than 15 Years
Total Population More than 18 Years -> Total Population More than 18 Years
Total Population More than 25 Years -> Total Population More than 25 Years
Total Population More than 35 Years -> Total Population More than 35 Years
Total Population More than 45 Years -> Total Population More than 45 Years
Total Population More than 55 Years -> Total Population More than 55 Years
Total Population More than 65 Years -> Total Population More than 65 Years
Total Population More than 75 Years -> Total Population More than 75 Years
Total Population More than 85 Years -> Total Population More than 85 Years
Total -> Total
Total Under 5 Years -> Total Under 5 Years
Total 5 to 9 Years -> Total 5 to 9 Years
Total 10 to 14 Years -> Total 10 to 14 Years
Total 15 to 17 Years -> Total 15 to 17 Years
Total 18 and 19 Years -> Total 18 and 19 Years
Total 20 Years -> Total 20 Years
Total 21 Years -> Total 21 Years
Total 22 to 24 Years -> Total 22 to 24 Years
Total 25 to 29 Years -> Total 25 to 29 Years
Total 30 to 34 Years -> Total 30 to 34 Years
Total 35 to 39 Years -> Total 35 to 39 Years
Total 40 to 44 Years -> Total 40 to 44 Years
Total 45 to 49 Years -> Total 45 to 49 Years
Total 50 to 54 Years -> Total 50 to 54 Years
Total 55 to 59 Years -> Total 55 to 59 Years
Total 60 and 61 Years -> Total 60 and 61 Years
Total 62 to 64 Years -> Total 62 to 64 Years
Total 65 and 66 Years -> Total 65 and 66 Years
Total 67 to 69 Years -> Total 67 to 69 Years
Total 70 to 74 Years -> Total 70 to 74 Years
Total 75 to 79 Years -> Total 75 to 79 Years
Total 80 to 84 Years -> Total 80 to 84 Years
Total 85 Years and Over -> Total 85 Years and Over
Total -> Total
Total Less than 5 Years -> Total Less than 5 Years
Total Less than 10 Years -> Total Less than 10 Years
Total Less than 15 Years -> Total Less than 15 Years
Total Less than 18 Years -> Total Less than 18 Years
Total Less than 20 Years -> Total Less than 20 Years
Total Less than 21 Years -> Total Less than 21 Years
Total Less than 22 Years -> Total Less than 22 Years
Total Less than 25 Years -> Total Less than 25 Years
Total Less than 30 Years -> Total Less than 30 Years
Total Less than 35 Years -> Total Less than 35 Years
Total Less than 40 Years -> Total Less than 40 Years
Total Less than 45 Years -> Total Less than 45 Years
Total Less than 50 Years -> Total Less than 50 Years
Total Less than 55 Years -> Total Less than 55 Years
Total Less than 60 Years -> Total Less than 60 Years
Total Less than 62 Years -> Total Less than 62 Years
Total Less than 65 Years -> Total Less than 65 Years
Total Less than 67 Years -> Total Less than 67 Years
Total Less than 70 Years -> Total Less than 70 Years
Total Less than 75 Years -> Total Less than 75 Years
Total Less than 80 Years -> Total Less than 80 Years
Total Less than 85 Years -> Total Less than 85 Years
Total -> Total
Total More than 5 Years -> Total More than 5 Years
Total More than 10 Years -> Total More than 10 Years
Total More than 15 Years -> Total More than 15 Years
Total More than 18 Years -> Total More than 18 Years
Total More than 20 Years -> Total More than 20 Years
Total More than 21 Years -> Total More than 21 Years
Total More than 22 Years -> Total More than 22 Years
Total More than 25 Years -> Total More than 25 Years
Total More than 30 Years -> Total More than 30 Years
Total More than 35 Years -> Total More than 35 Years
Total More than 40 Years -> Total More than 40 Years
Total More than 45 Years -> Total More than 45 Years
Total More than 50 Years -> Total More than 50 Years
Total More than 55 Years -> Total More than 55 Years
Total More than 60 Years -> Total More than 60 Years
Total More than 62 Years -> Total More than 62 Years
Total More than 65 Years -> Total More than 65 Years
Total More than 67 Years -> Total More than 67 Years
Total More than 70 Years -> Total More than 70 Years
Total More than 75 Years -> Total More than 75 Years
Total More than 80 Years -> Total More than 80 Years
Total More than 85 Years -> Total More than 85 Years
Total Population -> Total Population
Total Population Under 18 Years -> Total Population Under 18 Years
Total Population 18 to 34 Years -> Total Population 18 to 34 Years
Total Population 35 to 64 Years -> Total Population 35 to 64 Years
Total Population 65 and Over -> Total Population 65 and Over
Male Population -> Male Population
Male Population Under 18 Years -> Male Population Under 18 Years
Male Population 18 to 34 Years -> Male Population 18 to 34 Years
Male Population 35 to 64 Years -> Male Population 35 to 64 Years
Male Population 65 and Over -> Male Population 65 and Over
Female Population -> Female Population
Female Population Under 18 Years -> Female Population Under 18 Years
Female Population 18 to 34 Years -> Female Population 18 to 34 Years
Female Population 35 to 64 Years -> Female Population 35 to 64 Years
Female Population 65 and Over -> Female Population 65 and Over
Median Age -> Median Age
Median Age Male Population -> Median Age Male Population
Median Age Female Population -> Median Age Female Population
Total Population -> Total Population
Total Population White Alone -> Total Population White Alone
Total Population Black or African American Alone -> Total Population Black or African American Alone
Total Population American Indian and Alaska Native Alone -> Total Population American Indian and Alaska Native Alone
Total Population Asian Alone -> Total Population Asian Alone
Total Population Native Hawaiian and Other Pacific Islander Alone -> Total Population Native Hawaiian and Other Pacific Islander Alone
Total Population Some Other Race Alone -> Total Population Some Other Race Alone
Total Population Two or More Races -> Total Population Two or More Races
Total Population -> Total Population
Total Population Not Hispanic or Latino -> Total Population Not Hispanic or Latino
Total Population Not Hispanic or Latino White Alone -> Total Population Not Hispanic or Latino White Alone
Total Population Not Hispanic or Latino Black or African American Alone -> Total Population Not Hispanic or Latino Black or African American Alone
Total Population Not Hispanic or Latino American Indian and Alaska Native Alone -> Total Population Not Hispanic or Latino American Indian and Alaska Native Alone
Total Population Not Hispanic or Latino Asian Alone -> Total Population Not Hispanic or Latino Asian Alone
Total Population Not Hispanic or Latino Native Hawaiian and Other Pacific Islander Alone -> Total Population Not Hispanic or Latino Native Hawaiian and Other Pacific Islander Alone
Total Population Not Hispanic or Latino Some Other Race Alone -> Total Population Not Hispanic or Latino Some Other Race Alone
Total Population Not Hispanic or Latino Two or More Races -> Total Population Not Hispanic or Latino Two or More Races
Total Population Hispanic or Latino -> Total Population Hispanic or Latino
Total Population Hispanic or Latino White Alone -> Total Population Hispanic or Latino White Alone
Total Population Hispanic or Latino Black or African American Alone -> Total Population Hispanic or Latino Black or African American Alone
Total Population Hispanic or Latino American Indian and Alaska Native Alone -> Total Population Hispanic or Latino American Indian and Alaska Native Alone
Total Population Hispanic or Latino Asian Alone -> Total Population Hispanic or Latino Asian Alone
Total Population Hispanic or Latino Native Hawaiian and Other Pacific Islander Alone -> Total Population Hispanic or Latino Native Hawaiian and Other Pacific Islander Alone
Total Population Hispanic or Latino Some Other Race Alone -> Total Population Hispanic or Latino Some Other Race Alone
Total Population Hispanic or Latino Two or More Races -> Total Population Hispanic or Latino Two or More Races
Total Population -> Total Population
Total Population Not Hispanic or Latino -> Total Population Not Hispanic or Latino
Total Population Hispanic or Latino -> Total Population Hispanic or Latino
Total Population Hispanic or Latino Mexican -> Total Population Hispanic or Latino Mexican
Total Population Hispanic or Latino Puerto Rican -> Total Population Hispanic or Latino Puerto Rican
Total Population Hispanic or Latino Cuban -> Total Population Hispanic or Latino Cuban
Total Population Hispanic or Latino Dominican Republic -> Total Population Hispanic or Latino Dominican Republic
Total Population Hispanic or Latino Central American -> Total Population Hispanic or Latino Central American
Total Population Hispanic or Latino Central American Costa Rican -> Total Population Hispanic or Latino Central American Costa Rican
Total Population Hispanic or Latino Central American Guatemalan -> Total Population Hispanic or Latino Central American Guatemalan
Total Population Hispanic or Latino Central American Honduran -> Total Population Hispanic or Latino Central American Honduran
Total Population Hispanic or Latino Central American Nicaraguan -> Total Population Hispanic or Latino Central American Nicaraguan
Total Population Hispanic or Latino Central American Panamanian -> Total Population Hispanic or Latino Central American Panamanian
Total Population Hispanic or Latino Central American Salvadoran -> Total Population Hispanic or Latino Central American Salvadoran
Total Population Hispanic or Latino Central American Other Central American -> Total Population Hispanic or Latino Central American Other Central American
Total Population Hispanic or Latino South American -> Total Population Hispanic or Latino South American
Total Population Hispanic or Latino South American Argentinean -> Total Population Hispanic or Latino South American Argentinean
Total Population Hispanic or Latino South American Bolivian -> Total Population Hispanic or Latino South American Bolivian
Total Population Hispanic or Latino South American Chilean -> Total Population Hispanic or Latino South American Chilean
Total Population Hispanic or Latino South American Colombian -> Total Population Hispanic or Latino South American Colombian
Total Population Hispanic or Latino South American Ecuadorian -> Total Population Hispanic or Latino South American Ecuadorian
Total Population Hispanic or Latino South American Paraguayan -> Total Population Hispanic or Latino South American Paraguayan
Total Population Hispanic or Latino South American Peruvian -> Total Population Hispanic or Latino South American Peruvian
Total Population Hispanic or Latino South American Uruguayan -> Total Population Hispanic or Latino South American Uruguayan
Total Population Hispanic or Latino South American Venezuelan -> Total Population Hispanic or Latino South American Venezuelan

In [35]:
puma_df = acs1_df.combine_first(acs5_df)

In [36]:
# look at effect of combine first the 1-year ACS data with the 5-year ACS data
before_na = acs1_df.isna()
after_na = puma_df.isna()
filled_mask = before_na & ~after_na

filled_cols = filled_mask.any(axis=0)
for col in filled_cols[filled_cols].index.tolist():
    print(f"{col}: {before_na[col].sum()} -> {after_na[col].sum()}")
print()
print(acs1_df.isna().sum().sum(), puma_df.isna().sum().sum())

2.00 to 2.99.SE_C13004_003: 257 -> 0
3.00 to 3.99.SE_C13004_004: 257 -> 0
4.00 to 4.99.SE_C13004_005: 257 -> 0
5.00 and Over.SE_C13004_006: 257 -> 0
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) American Indian and Alaska Native Alone  Householder.SE_A14019_004: 1633 -> 109
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Asian Alone Householder.SE_A14019_005: 396 -> 3
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Black or African American Alone Householder.SE_A14019_003: 227 -> 5
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Native Hawaiian and Other Pacific Islander Alone  Householder.SE_A14019_006: 2252 -> 1604
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Some Other Race Alone Householder.SE_A14019_007: 605 -> 11
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008: 260 -> 0
American Indian and Alaska Native 16 Years Old in  Civilian Labor Force Employed.SE_A17006C_002: 2283 -> 1
American Indian and Alaska Native 16 Years Old in  Civilian Labor Force Unemployed.SE_A17006C_003: 2283 -> 1
American Indian and Alaska Native 16 Years Old in  Civilian Labor Force.SE_A17006C_001: 2283 -> 1
American Indian and Alaska Native Alone  Population for Whom Poverty Status Is Determined.SE_A13001C_001: 2300 -> 2
Asian 16 Years Old in Civilian Labor Force Employed.SE_A17006D_002: 2021 -> 3
Asian 16 Years Old in Civilian Labor Force Unemployed.SE_A17006D_003: 2021 -> 3
Asian 16 Years Old in Civilian Labor Force.SE_A17006D_001: 2021 -> 3
Asian Alone Population for Whom Poverty Status Is  Determined.SE_A13001D_001: 2239 -> 3
Average Commute to Work (In Min).SE_A09003_001: 2225 -> 3
Average Family Income (In 2018 Inflation Adjusted Dollars).SE_A14011_001: 2 -> 0
Average Gross Rent for Renter-Occupied Housing Units.SE_A18005_001: 2 -> 0
Average Household Income (In 2018 Inflation Adjusted Dollars) American Indian and Alaska Native Alone  Householder.SE_A14009_004: 2292 -> 12
Average Household Income (In 2018 Inflation Adjusted Dollars) Asian Alone.SE_A14009_005: 2071 -> 3
Average Household Income (In 2018 Inflation Adjusted Dollars) Black or African American Alone Householder.SE_A14009_003: 1573 -> 3
Average Household Income (In 2018 Inflation Adjusted Dollars) Native Hawaiian and Other Pacific Islander Alone  Householder.SE_A14009_006: 2336 -> 624
Average Household Income (In 2018 Inflation Adjusted Dollars) Some Other Race Alone Householder.SE_A14009_007: 2151 -> 2
Average Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14009_008: 2309 -> 3
Average Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14009_002: 15 -> 0
Average Nonfamily Income (In 2018 Inflation Adjusted Dollars).SE_A14013_001: 19 -> 0
Black or African American 16 Years Old in  Civilian Labor Force Employed.SE_A17006B_002: 1542 -> 3
Black or African American 16 Years Old in  Civilian Labor Force Unemployed.SE_A17006B_003: 1542 -> 3
Black or African American 16 Years Old in  Civilian Labor Force.SE_A17006B_001: 1542 -> 3
Black or African American Alone Population for  Whom Poverty Status Is Determined.SE_A13001B_001: 1904 -> 3
Civilian Female in Labor Force 16 Years and Over Employed.SE_A17005B_002: 312 -> 0
Civilian Female in Labor Force 16 Years and Over Unemployed.SE_A17005B_003: 312 -> 0
Civilian Female in Labor Force 16 Years and Over.SE_A17005B_001: 312 -> 0
Civilian Male in Labor Force 16 Years and Over Employed.SE_A17005A_002: 312 -> 0
Civilian Male in Labor Force 16 Years and Over Unemployed.SE_A17005A_003: 312 -> 0
Civilian Male in Labor Force 16 Years and Over.SE_A17005A_001: 312 -> 0
Civilian Population 16 to 19 Years High School Graduate, or Enrolled (In School).SE_A12003_003: 2269 -> 3
Civilian Population 16 to 19 Years Not High School Graduate, Not Enrolled (Dropped Out).SE_A12003_002: 2269 -> 3
Civilian Population 16 to 19 Years.SE_A12003_001: 2269 -> 3
Civilian Veterans 18 Years and Over Gulf War 1990 to 2001 Only.SE_A16001_003: 1390 -> 0
Civilian Veterans 18 Years and Over Gulf War 2001 or Later Only.SE_A16001_002: 1390 -> 0
Civilian Veterans 18 Years and Over Korean War Only.SE_A16001_005: 1390 -> 0
Civilian Veterans 18 Years and Over Other Service.SE_A16001_008: 1390 -> 0
Civilian Veterans 18 Years and Over Served in Multiple Wars.SE_A16001_007: 1390 -> 0
Civilian Veterans 18 Years and Over Vietnam Era Only.SE_A16001_004: 1390 -> 0
Civilian Veterans 18 Years and Over.SE_A16001_001: 1390 -> 0
Employed Civilian Population 16 Years and Over Building and Grounds Cleaning and Maintenance  Occupations.SE_B17008_007: 4 -> 0
Employed Civilian Population 16 Years and Over Construction, Extraction, and Maintenance  Occupations.SE_A17008_006: 4 -> 0
Employed Civilian Population 16 Years and Over Construction, Extraction, and Maintenance  Occupations.SE_B17008_012: 4 -> 0
Employed Civilian Population 16 Years and Over Farming, Fishing, and Forestry Occupations.SE_A17008_005: 4 -> 0
Employed Civilian Population 16 Years and Over Farming, Fishing, and Forestry Occupations.SE_B17008_011: 4 -> 0
Employed Civilian Population 16 Years and Over Food Preparation and Serving Related Occupations.SE_B17008_006: 4 -> 0
Employed Civilian Population 16 Years and Over Healthcare Support Occupations.SE_B17008_004: 4 -> 0
Employed Civilian Population 16 Years and Over Management, Business, and Financial Operations  Occupations.SE_B17008_002: 4 -> 0
Employed Civilian Population 16 Years and Over Management, Professional, and Related Occupations.SE_A17008_002: 4 -> 0
Employed Civilian Population 16 Years and Over Office and Administrative Support Occupations.SE_B17008_010: 4 -> 0
Employed Civilian Population 16 Years and Over Personal Care and Service Occupations.SE_B17008_008: 4 -> 0
Employed Civilian Population 16 Years and Over Production Occupations.SE_B17008_013: 4 -> 0
Employed Civilian Population 16 Years and Over Production, Transportation, and Material Moving  Occupations Production Occupations.SE_A17008_008: 4 -> 0
Employed Civilian Population 16 Years and Over Production, Transportation, and Material Moving  Occupations Transportation and Material Moving Occupations.SE_A17008_009: 4 -> 0
Employed Civilian Population 16 Years and Over Production, Transportation, and Material Moving  Occupations.SE_A17008_007: 4 -> 0
Employed Civilian Population 16 Years and Over Professional and Related Occupations.SE_B17008_003: 4 -> 0
Employed Civilian Population 16 Years and Over Protective Service Occupations.SE_B17008_005: 4 -> 0
Employed Civilian Population 16 Years and Over Sales and Office Occupations.SE_A17008_004: 4 -> 0
Employed Civilian Population 16 Years and Over Sales and Related Occupations.SE_B17008_009: 4 -> 0
Employed Civilian Population 16 Years and Over Service Occupations.SE_A17008_003: 4 -> 0
Employed Civilian Population 16 Years and Over Transportation and Material Moving Occupations.SE_B17008_014: 4 -> 0
Employed Civilian Population 16 Years and Over.SE_A17008_001: 4 -> 0
Employed Civilian Population 16 Years and Over.SE_B17008_001: 4 -> 0
Families .50 to .74.SE_E13004_003: 13 -> 0
Families .75 to .99.SE_E13004_004: 13 -> 0
Families 1.00 to 1.49.SE_E13004_005: 13 -> 0
Families 1.00 to 1.99 (Struggling).SE_F13004_003: 13 -> 0
Families 1.50 to 1.99.SE_E13004_006: 13 -> 0
Families 2.00 and Over (Doing Ok).SE_F13004_005: 13 -> 0
Families 2.00 and Over.SE_E13004_007: 13 -> 0
Families Under .50.SE_E13004_002: 13 -> 0
Families Under 1.00 (Doing Poorly).SE_F13004_002: 13 -> 0
Families Under 2.00 (Poor or Struggling).SE_F13004_004: 13 -> 0
Families.SE_A13002_001: 737 -> 0
Families.SE_D13004_001: 13 -> 0
Families.SE_E13004_001: 13 -> 0
Families.SE_F13004_001: 13 -> 0
Female Civilian Population 16 to 19 Years High School Graduate, or Enrolled (In School).SE_A12003B_003: 2269 -> 3
Female Civilian Population 16 to 19 Years Not High School Graduate, Not Enrolled (Dropped Out).SE_A12003B_002: 2269 -> 3
Female Civilian Population 16 to 19 Years.SE_A12003B_001: 2269 -> 3
Female Employed Civilian Population 16 Years and Over Building and Grounds Cleaning and Maintenance  Occupations.SE_A17007B_007: 4 -> 0
Female Employed Civilian Population 16 Years and Over Farming, Fishing, and Forestry Occupations.SE_A17007B_011: 4 -> 0
Female Employed Civilian Population 16 Years and Over Food Preparation and Serving Related Occupations.SE_A17007B_006: 4 -> 0
Female Employed Civilian Population 16 Years and Over Healthcare Support Occupations.SE_A17007B_004: 4 -> 0
Female Employed Civilian Population 16 Years and Over Management, Business, and Financial Operations  Occupations.SE_A17007B_002: 4 -> 0
Female Employed Civilian Population 16 Years and Over Office and Administrative Support Occupations.SE_A17007B_010: 4 -> 0
Female Employed Civilian Population 16 Years and Over Personal Care and Service Occupations.SE_A17007B_008: 4 -> 0
Female Employed Civilian Population 16 Years and Over Production Occupations.SE_A17007B_013: 4 -> 0
Female Employed Civilian Population 16 Years and Over Professional and Related Occupations.SE_A17007B_003: 4 -> 0
Female Employed Civilian Population 16 Years and Over Protective Service Occupations.SE_A17007B_005: 4 -> 0
Female Employed Civilian Population 16 Years and Over Sales and Related Occupations.SE_A17007B_009: 4 -> 0
Female Employed Civilian Population 16 Years and Over Transportation and Material Moving Occupations.SE_A17007B_014: 4 -> 0
Female Employed Civilian Population 16 Years and Over.SE_A17007B_001: 4 -> 0
Female Population 16 Years and Over Not in Labor Force.SE_A17002B_007: 312 -> 0
Female Population 16 Years and Over in Labor Force Civilian Employed.SE_A17002B_005: 312 -> 0
Female Population 16 Years and Over in Labor Force Civilian Unemployed.SE_A17002B_006: 312 -> 0
Female Population 16 Years and Over in Labor Force Civilian.SE_A17002B_004: 312 -> 0
Female Population 16 Years and Over in Labor Force in Armed Forces.SE_A17002B_003: 312 -> 0
Female Population 16 Years and Over in Labor Force.SE_A17002B_002: 312 -> 0
Female Population 16 Years and Over.SE_A17002B_001: 312 -> 0
Foreign-Born Population 1990 to 1999.SE_A10058_004: 327 -> 0
Foreign-Born Population 2000 to 2009.SE_A10058_003: 327 -> 0
Foreign-Born Population 2010 or Later.SE_A10058_002: 327 -> 0
Foreign-Born Population Africa Eastern Africa Ethiopia.SE_A07001_069: 2336 -> 0
Foreign-Born Population Africa Eastern Africa Kenya.SE_A07001_070: 2336 -> 0
Foreign-Born Population Africa Eastern Africa Other Eastern Africa.SE_A07001_071: 2336 -> 0
Foreign-Born Population Africa Eastern Africa.SE_A07001_068: 2336 -> 0
Foreign-Born Population Africa Middle Africa.SE_A07001_072: 2336 -> 0
Foreign-Born Population Africa Northern Africa Egypt.SE_A07001_074: 2336 -> 0
Foreign-Born Population Africa Northern Africa Other Northern Africa.SE_A07001_075: 2336 -> 0
Foreign-Born Population Africa Northern Africa.SE_A07001_073: 2336 -> 0
Foreign-Born Population Africa Southern Africa Other Southern Africa.SE_A07001_078: 2336 -> 0
Foreign-Born Population Africa Southern Africa South Africa.SE_A07001_077: 2336 -> 0
Foreign-Born Population Africa Southern Africa.SE_A07001_076: 2336 -> 0
Foreign-Born Population Africa Western Africa Ghana.SE_A07001_080: 2336 -> 0
Foreign-Born Population Africa Western Africa Liberia.SE_A07001_081: 2336 -> 0
Foreign-Born Population Africa Western Africa Nigeria.SE_A07001_082: 2336 -> 0
Foreign-Born Population Africa Western Africa Other Western Africa.SE_A07001_083: 2336 -> 0
Foreign-Born Population Africa Western Africa.SE_A07001_079: 2336 -> 0
Foreign-Born Population Africa.SE_A07001_067: 2336 -> 0
Foreign-Born Population Americas Latin America.SE_A07001_091: 2336 -> 0
Foreign-Born Population Americas Northern America Canada.SE_A07001_122: 2336 -> 0
Foreign-Born Population Americas Northern America Other Northern America.SE_A07001_123: 2336 -> 0
Foreign-Born Population Americas Northern America.SE_A07001_121: 2336 -> 0
Foreign-Born Population Americas.SE_A07001_090: 2336 -> 0
Foreign-Born Population Asia Eastern Asia China China, Excluding Hong Kong and Taiwan.SE_A07001_037: 2336 -> 0
Foreign-Born Population Asia Eastern Asia China Hong Kong.SE_A07001_038: 2336 -> 0
Foreign-Born Population Asia Eastern Asia China Taiwan.SE_A07001_039: 2336 -> 0
Foreign-Born Population Asia Eastern Asia China.SE_A07001_036: 2336 -> 0
Foreign-Born Population Asia Eastern Asia Japan.SE_A07001_040: 2336 -> 0
Foreign-Born Population Asia Eastern Asia Korea.SE_A07001_041: 2336 -> 0
Foreign-Born Population Asia Eastern Asia Other Eastern Asia.SE_A07001_042: 2336 -> 0
Foreign-Born Population Asia Eastern Asia.SE_A07001_035: 2336 -> 0
Foreign-Born Population Asia South Central Asia Afghanistan.SE_A07001_044: 2336 -> 0
Foreign-Born Population Asia South Central Asia Bangladesh.SE_A07001_045: 2336 -> 0
Foreign-Born Population Asia South Central Asia India.SE_A07001_046: 2336 -> 0
Foreign-Born Population Asia South Central Asia Iran.SE_A07001_047: 2336 -> 0
Foreign-Born Population Asia South Central Asia Other South Central Asia.SE_A07001_049: 2336 -> 0
Foreign-Born Population Asia South Central Asia Pakistan.SE_A07001_048: 2336 -> 0
Foreign-Born Population Asia South Central Asia.SE_A07001_043: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia Cambodia.SE_A07001_051: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia Indonesia.SE_A07001_052: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia Laos.SE_A07001_053: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia Other South Eastern Asia.SE_A07001_057: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia Philippines.SE_A07001_054: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia Thailand.SE_A07001_055: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia Vietnam.SE_A07001_056: 2336 -> 0
Foreign-Born Population Asia South Eastern Asia.SE_A07001_050: 2336 -> 0
Foreign-Born Population Asia Western Asia Armenia.SE_A07001_064: 2336 -> 0
Foreign-Born Population Asia Western Asia Iraq.SE_A07001_059: 2336 -> 0
Foreign-Born Population Asia Western Asia Israel.SE_A07001_060: 2336 -> 0
Foreign-Born Population Asia Western Asia Lebanon.SE_A07001_061: 2336 -> 0
Foreign-Born Population Asia Western Asia Other Western Asia.SE_A07001_065: 2336 -> 0
Foreign-Born Population Asia Western Asia Syria.SE_A07001_062: 2336 -> 0
Foreign-Born Population Asia Western Asia Turkey.SE_A07001_063: 2336 -> 0
Foreign-Born Population Asia Western Asia.SE_A07001_058: 2336 -> 0
Foreign-Born Population Asia.SE_A07001_034: 2336 -> 0
Foreign-Born Population Before 1990.SE_A10058_005: 327 -> 0
Foreign-Born Population Europe Eastern Europe Bosnia and Herzegovina.SE_A07001_030: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Croatia.SE_A07001_023: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Czechoslovakia (Includes Czech Republic and Slovakia).SE_A07001_024: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Hungary.SE_A07001_025: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Other Eastern Europe.SE_A07001_032: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Poland.SE_A07001_026: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Romania.SE_A07001_027: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Russia.SE_A07001_028: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Serbia.SE_A07001_031: 2336 -> 0
Foreign-Born Population Europe Eastern Europe Ukraine.SE_A07001_029: 2336 -> 0
Foreign-Born Population Europe Eastern Europe.SE_A07001_022: 2336 -> 0
Foreign-Born Population Europe Northern Europe Ireland.SE_A07001_008: 2336 -> 0
Foreign-Born Population Europe Northern Europe Other Northern Europe.SE_A07001_009: 2336 -> 0
Foreign-Born Population Europe Northern Europe United Kingdom England.SE_A07001_006: 2336 -> 0
Foreign-Born Population Europe Northern Europe United Kingdom Scotland.SE_A07001_007: 2336 -> 0
Foreign-Born Population Europe Northern Europe United Kingdom United Kingdom, Excluding England and Scotland.SE_A07001_005: 2336 -> 0
Foreign-Born Population Europe Northern Europe United Kingdom.SE_A07001_004: 2336 -> 0
Foreign-Born Population Europe Northern Europe.SE_A07001_003: 2336 -> 0
Foreign-Born Population Europe Southern Europe Greece.SE_A07001_017: 2336 -> 0
Foreign-Born Population Europe Southern Europe Italy.SE_A07001_018: 2336 -> 0
Foreign-Born Population Europe Southern Europe Other Southern Europe.SE_A07001_021: 2336 -> 0
Foreign-Born Population Europe Southern Europe Portugal.SE_A07001_019: 2336 -> 0
Foreign-Born Population Europe Southern Europe Spain.SE_A07001_020: 2336 -> 0
Foreign-Born Population Europe Southern Europe.SE_A07001_016: 2336 -> 0
Foreign-Born Population Europe Western Europe Austria.SE_A07001_011: 2336 -> 0
Foreign-Born Population Europe Western Europe France.SE_A07001_012: 2336 -> 0
Foreign-Born Population Europe Western Europe Germany.SE_A07001_013: 2336 -> 0
Foreign-Born Population Europe Western Europe Netherlands.SE_A07001_014: 2336 -> 0
Foreign-Born Population Europe Western Europe Other Western Europe.SE_A07001_015: 2336 -> 0
Foreign-Born Population Europe Western Europe.SE_A07001_010: 2336 -> 0
Foreign-Born Population Europe.SE_A07001_002: 2336 -> 0
Foreign-Born Population Oceania Australia and New Zealand Subregion Australia.SE_A07001_087: 2336 -> 0
Foreign-Born Population Oceania Australia and New Zealand Subregion Other Australian and New Zealand Subregion.SE_A07001_088: 2336 -> 0
Foreign-Born Population Oceania Australia and New Zealand Subregion.SE_A07001_086: 2336 -> 0
Foreign-Born Population Oceania.SE_A07001_085: 2336 -> 0
Foreign-Born Population.SE_A07001_001: 2336 -> 0
Foreign-Born Population.SE_A10058_001: 327 -> 0
Hispanic or Latino 16 Years Old in Civilian Labor Force Employed.SE_A17006H_002: 1518 -> 0
Hispanic or Latino 16 Years Old in Civilian Labor Force Unemployed.SE_A17006H_003: 1518 -> 0
Hispanic or Latino 16 Years Old in Civilian Labor Force.SE_A17006H_001: 1518 -> 0
Hispanic or Latino Population for Whom Poverty  Status Is Determined.SE_A13001H_001: 1716 -> 0
Households All Other Households.SE_A11002_009: 18 -> 0
Households Unmarried-Partner Households Opposite Sex Partners Female Householder and Male Partner.SE_A11002_008: 18 -> 0
Households Unmarried-Partner Households Opposite Sex Partners Male Householder and Female Partner.SE_A11002_007: 18 -> 0
Households Unmarried-Partner Households Opposite Sex Partners.SE_A11002_006: 18 -> 0
Households Unmarried-Partner Households Same Sex Partners Female Householder and Female Partner.SE_A11002_005: 18 -> 0
Households Unmarried-Partner Households Same Sex Partners Male Householder and Male Partner.SE_A11002_004: 18 -> 0
Households Unmarried-Partner Households Same Sex Partners.SE_A11002_003: 18 -> 0
Households Unmarried-Partner Households.SE_A11002_002: 18 -> 0
Households with a Householder Who Is American Indian and  Alaska Native Alone.SE_A10010_004: 2209 -> 0
Households with a Householder Who Is Asian Alone.SE_A10010_005: 1656 -> 0
Households with a Householder Who Is Black or African  American Alone.SE_A10010_003: 894 -> 0
Households with a Householder Who Is Hispanic or Latino.SE_A10010_009: 645 -> 0
Households with a Householder Who Is Native Hawaiian and  Other Pacific Islander Alone.SE_A10010_006: 2334 -> 0
Households with a Householder Who Is Some Other Race Alone.SE_A10010_007: 1729 -> 0
Households with a Householder Who Is Two or More Races.SE_A10010_008: 1809 -> 0
Households with a Householder Who Is White Alone, Not  Hispanic or Latino.SE_A10010_010: 35 -> 0
Households with a Householder Who Is White Alone.SE_A10010_002: 3 -> 0
Households.SE_A11002_001: 18 -> 0
Housing Units 1 Unit 1, Attached.SE_A10032_004: 11 -> 0
Housing Units 1 Unit 1, Detached.SE_A10032_003: 11 -> 0
Housing Units 1 Unit.SE_A10032_002: 11 -> 0
Housing Units 10 to 19.SE_A10032_008: 11 -> 0
Housing Units 2.SE_A10032_005: 11 -> 0
Housing Units 20 to 49.SE_A10032_009: 11 -> 0

In [37]:
def inject_titles(col):
    """Function to inject titles into the column names of the ACS 1-year data."""
    key = col.split(".")[-1].split("_")[1]
    title = acs1_code_to_name["Title"].get(key, None)
    if title is not None:
        return title + "." + col
    return col


puma_df = puma_df.rename(columns=inject_titles)

In [38]:
# drop columns where measurements are suppressed or not available for any PUMA
old_columns = set(puma_df.columns)
puma_df = puma_df.dropna(axis=1)
for col in sorted(old_columns - set(puma_df.columns)):
    print(f"Dropped column: {col}")

Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) American Indian and Alaska Native Alone  Householder.SE_A14019_004
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Asian Alone Householder.SE_A14019_005
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Black or African American Alone Householder.SE_A14019_003
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Hispanic or Latino Householder.SE_A14019_009
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Native Hawaiian and Other Pacific Islander Alone  Householder.SE_A14019_006
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Some Other Race Alone Householder.SE_A14019_007
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone, Not Hispanic or Latino Householder.SE_A14019_010
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation-Adjusted Dollars) Hispanic or Latino Householder.SE_A14019_009
Dropped column: Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation-Adjusted Dollars) White Alone, Not Hispanic or Latino Householder.SE_A14019_010
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over American Indian and Alaska Native Alone.SE_A14023_004
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over Asian Alone.SE_A14023_005
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over Black or African American Alone.SE_A14023_003
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over Hispanic or Latino.SE_A14023_009
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over Native Hawaiian and Other Pacific Islander Alone.SE_A14023_006
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over Some Other Race Alone.SE_A14023_007
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over Two or More Races.SE_A14023_008
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over White Alone, Not Hispanic or Latino.SE_A14023_010
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) For&nbsp; Population 15 Years and Over White Alone.SE_A14023_002
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over American Indian and Alaska Native Alone.SE_A14023_004
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over Asian Alone.SE_A14023_005
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over Black or African American Alone Population 15  Years and Over.SE_A14023_003
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over Native Hawaiian and Other Pacific Islander Alone.SE_A14023_006
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over Some Other Race Alone.SE_A14023_007
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over Two or More Races.SE_A14023_008
Dropped column: Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation-Adjusted Dollars) for Population 15 Years and Over Hispanic or Latino.SE_A14023_009
Dropped column: Alaska Native Regional Corporation (FIPS).Geo_ANRC
Dropped column: American Indian Area/Alaska Native Area/Hawaiian Home Land (Census).Geo_AIANHH
Dropped column: American Indian Area/Alaska Native Area/Hawaiian Home Land (FIPS).Geo_AIANHHFP
Dropped column: American Indian Tribal Subdivision (Census).Geo_AITSCE
Dropped column: American Indian Tribal Subdivision (FIPS).Geo_AITS
Dropped column: American Indian Trust Land/Hawaiian Home Land Indicator.Geo_AIHHTLI
Dropped column: American Indian and Alaska Native Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Female.SE_A13005C_007
Dropped column: American Indian and Alaska Native Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male.SE_A13005C_006
Dropped column: American Indian and Alaska Native Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level.SE_A13005C_005
Dropped column: American Indian and Alaska Native Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Female.SE_A13005C_004
Dropped column: American Indian and Alaska Native Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male.SE_A13005C_003
Dropped column: American Indian and Alaska Native Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level.SE_A13005C_002
Dropped column: American Indian and Alaska Native Alone Population for Whom Poverty Status Is Determined.SE_A13005C_001
Dropped column: Asian Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Female.SE_A13005D_007
Dropped column: Asian Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male.SE_A13005D_006
Dropped column: Asian Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level.SE_A13005D_005
Dropped column: Asian Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Female.SE_A13005D_004
Dropped column: Asian Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male.SE_A13005D_003
Dropped column: Asian Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level.SE_A13005D_002
Dropped column: Asian Alone Population for Whom Poverty Status Is Determined.SE_A13005D_001
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Asian Indian.SE_A03002_002
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Bangladeshi.SE_A03002_003
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Bhutanese.SE_A03002_004
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Burmese.SE_A03002_005
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Cambodian.SE_A03002_006
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Chinese, Except Taiwanese.SE_A03002_007
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Filipino.SE_A03002_008
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Hmong.SE_A03002_009
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Indonesian.SE_A03002_010
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Japanese.SE_A03002_011
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Korean.SE_A03002_012
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Laotian.SE_A03002_013
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Malaysian.SE_A03002_014
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Mongolian.SE_A03002_015
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Nepalese.SE_A03002_016
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Okinawan.SE_A03002_017
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Other Asian, Not Specified.SE_A03002_024
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Other Asian, Specified.SE_A03002_023
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Pakistani.SE_A03002_018
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Sri Lankan.SE_A03002_019
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Taiwanese.SE_A03002_020
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Thai.SE_A03002_021
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Two or More Asian.SE_A03002_025
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population Vietnamese.SE_A03002_022
Dropped column: Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Alone Population.SE_A03002_001
Dropped column: Average Commute to Work (In Min).Average Commute to Work (In Min).SE_A09003_001
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) American Indian and Alaska Native Alone  Householder.SE_A14009_004
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) Asian Alone.SE_A14009_005
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) Black or African American Alone Householder.SE_A14009_003
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) Hispanic or Latino Householder.SE_A14009_009
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) Native Hawaiian and Other Pacific Islander Alone  Householder.SE_A14009_006
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) Some Other Race Alone Householder.SE_A14009_007
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14009_008
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder, Not Hispanic or Latino.SE_A14009_010
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation-Adjusted Dollars) Hispanic or Latino Householder.SE_A14009_009
Dropped column: Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation-Adjusted Dollars) White Alone Householder, Not Hispanic or Latino.SE_A14009_010
Dropped column: Black or African American Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Female.SE_A13005B_007
Dropped column: Black or African American Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male.SE_A13005B_006
Dropped column: Black or African American Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level.SE_A13005B_005
Dropped column: Black or African American Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Female.SE_A13005B_004
Dropped column: Black or African American Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male.SE_A13005B_003
Dropped column: Black or African American Alone Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level.SE_A13005B_002
Dropped column: Black or African American Alone Population for Whom Poverty Status Is Determined.SE_A13005B_001
Dropped column: Block Group.Geo_BLKGRP
Dropped column: Census Tract.Geo_TRACT
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male Not in Labor Force.SE_A13007_011
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male in Labor Force Employed.SE_A13007_009
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male in Labor Force Unemployed.SE_A13007_010
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male in Labor Force.SE_A13007_008
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level.SE_A13007_007
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male Not in Labor Force.SE_A13007_006
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male in Labor Force Employed.SE_A13007_004
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male in Labor Force Unemployed.SE_A13007_005
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male in Labor Force.SE_A13007_003
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level.SE_A13007_002
Dropped column: Civilian Population 16 Years and Over for Whom Poverty Status Is Determined.SE_A13007_001
Dropped column: Combined Statistical Area.Geo_CSA
Dropped column: Consolidated City.Geo_CONCIT
Dropped column: County Subdivision (FIPS).Geo_COUSUB
Dropped column: County.Geo_COUNTY
Dropped column: Current Congressional District ***.Geo_CDCURR
Dropped column: Current Congressional District 110.Geo_CDCURR
Dropped column: Division.Geo_DIVISION
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (Less).Less than $1,000.SE_A18001A_005
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (Less).Less than $1,250.SE_A18001A_006
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (Less).Less than $1,500.SE_A18001A_007
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (Less).Less than $2,000.SE_A18001A_008
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (Less).Less than $300.SE_A18001A_002
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (Less).Less than $600.SE_A18001A_003
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (Less).Less than $800.SE_A18001A_004
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (More).More than $1,000.SE_A18001B_005
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (More).More than $1,250.SE_A18001B_006
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (More).More than $1,500.SE_A18001B_007
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (More).More than $2,000.SE_A18001B_008
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (More).More than $300.SE_A18001B_002
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (More).More than $600.SE_A18001B_003
Dropped column: Gross Rent (Housing Units with Cash Rent) - Cumulative (More).More than $800.SE_A18001B_004
Dropped column: Hispanic or Latino Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Female.SE_A13005H_007
Dropped column: Hispanic or Latino Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level Male.SE_A13005H_006
Dropped column: Hispanic or Latino Population for Whom Poverty Status Is Determined Income in the Past 12 Months At or Above Poverty Level.SE_A13005H_005
Dropped column: Hispanic or Latino Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Female.SE_A13005H_004
Dropped column: Hispanic or Latino Population for Whom Poverty Status Is Determined Income in the Past 12 Months Below Poverty Level Male.SE_A13005H_003

In [39]:
# available columns
for col in sorted(puma_df.columns):
    print(col)

Age (Detailed Version) - Cumulative (Less).Total Less than 10 Years.SE_C01001A_003
Age (Detailed Version) - Cumulative (Less).Total Less than 15 Years.SE_C01001A_004
Age (Detailed Version) - Cumulative (Less).Total Less than 18 Years.SE_C01001A_005
Age (Detailed Version) - Cumulative (Less).Total Less than 20 Years.SE_C01001A_006
Age (Detailed Version) - Cumulative (Less).Total Less than 21 Years.SE_C01001A_007
Age (Detailed Version) - Cumulative (Less).Total Less than 22 Years.SE_C01001A_008
Age (Detailed Version) - Cumulative (Less).Total Less than 25 Years.SE_C01001A_009
Age (Detailed Version) - Cumulative (Less).Total Less than 30 Years.SE_C01001A_010
Age (Detailed Version) - Cumulative (Less).Total Less than 35 Years.SE_C01001A_011
Age (Detailed Version) - Cumulative (Less).Total Less than 40 Years.SE_C01001A_012
Age (Detailed Version) - Cumulative (Less).Total Less than 45 Years.SE_C01001A_013
Age (Detailed Version) - Cumulative (Less).Total Less than 5 Years.SE_C01001A_002
Age (Detailed Version) - Cumulative (Less).Total Less than 50 Years.SE_C01001A_014
Age (Detailed Version) - Cumulative (Less).Total Less than 55 Years.SE_C01001A_015
Age (Detailed Version) - Cumulative (Less).Total Less than 60 Years.SE_C01001A_016
Age (Detailed Version) - Cumulative (Less).Total Less than 62 Years.SE_C01001A_017
Age (Detailed Version) - Cumulative (Less).Total Less than 65 Years.SE_C01001A_018
Age (Detailed Version) - Cumulative (Less).Total Less than 67 Years.SE_C01001A_019
Age (Detailed Version) - Cumulative (Less).Total Less than 70 Years.SE_C01001A_020
Age (Detailed Version) - Cumulative (Less).Total Less than 75 Years.SE_C01001A_021
Age (Detailed Version) - Cumulative (Less).Total Less than 80 Years.SE_C01001A_022
Age (Detailed Version) - Cumulative (Less).Total Less than 85 Years.SE_C01001A_023
Age (Detailed Version) - Cumulative (Less).Total.SE_C01001A_001
Age (Detailed Version) - Cumulative (More).Total More than 10 Years.SE_C01001B_003
Age (Detailed Version) - Cumulative (More).Total More than 15 Years.SE_C01001B_004
Age (Detailed Version) - Cumulative (More).Total More than 18 Years.SE_C01001B_005
Age (Detailed Version) - Cumulative (More).Total More than 20 Years.SE_C01001B_006
Age (Detailed Version) - Cumulative (More).Total More than 21 Years.SE_C01001B_007
Age (Detailed Version) - Cumulative (More).Total More than 22 Years.SE_C01001B_008
Age (Detailed Version) - Cumulative (More).Total More than 25 Years.SE_C01001B_009
Age (Detailed Version) - Cumulative (More).Total More than 30 Years.SE_C01001B_010
Age (Detailed Version) - Cumulative (More).Total More than 35 Years.SE_C01001B_011
Age (Detailed Version) - Cumulative (More).Total More than 40 Years.SE_C01001B_012
Age (Detailed Version) - Cumulative (More).Total More than 45 Years.SE_C01001B_013
Age (Detailed Version) - Cumulative (More).Total More than 5 Years.SE_C01001B_002
Age (Detailed Version) - Cumulative (More).Total More than 50 Years.SE_C01001B_014
Age (Detailed Version) - Cumulative (More).Total More than 55 Years.SE_C01001B_015
Age (Detailed Version) - Cumulative (More).Total More than 60 Years.SE_C01001B_016
Age (Detailed Version) - Cumulative (More).Total More than 62 Years.SE_C01001B_017
Age (Detailed Version) - Cumulative (More).Total More than 65 Years.SE_C01001B_018
Age (Detailed Version) - Cumulative (More).Total More than 67 Years.SE_C01001B_019
Age (Detailed Version) - Cumulative (More).Total More than 70 Years.SE_C01001B_020
Age (Detailed Version) - Cumulative (More).Total More than 75 Years.SE_C01001B_021
Age (Detailed Version) - Cumulative (More).Total More than 80 Years.SE_C01001B_022
Age (Detailed Version) - Cumulative (More).Total More than 85 Years.SE_C01001B_023
Age (Detailed Version) - Cumulative (More).Total.SE_C01001B_001
Age (Detailed Version).Total 10 to 14 Years.SE_C01001_004
Age (Detailed Version).Total 15 to 17 Years.SE_C01001_005
Age (Detailed Version).Total 18 and 19 Years.SE_C01001_006
Age (Detailed Version).Total 20 Years.SE_C01001_007
Age (Detailed Version).Total 21 Years.SE_C01001_008
Age (Detailed Version).Total 22 to 24 Years.SE_C01001_009
Age (Detailed Version).Total 25 to 29 Years.SE_C01001_010
Age (Detailed Version).Total 30 to 34 Years.SE_C01001_011
Age (Detailed Version).Total 35 to 39 Years.SE_C01001_012
Age (Detailed Version).Total 40 to 44 Years.SE_C01001_013
Age (Detailed Version).Total 45 to 49 Years.SE_C01001_014
Age (Detailed Version).Total 5 to 9 Years.SE_C01001_003
Age (Detailed Version).Total 50 to 54 Years.SE_C01001_015
Age (Detailed Version).Total 55 to 59 Years.SE_C01001_016
Age (Detailed Version).Total 60 and 61 Years.SE_C01001_017
Age (Detailed Version).Total 62 to 64 Years.SE_C01001_018
Age (Detailed Version).Total 65 and 66 Years.SE_C01001_019
Age (Detailed Version).Total 67 to 69 Years.SE_C01001_020
Age (Detailed Version).Total 70 to 74 Years.SE_C01001_021
Age (Detailed Version).Total 75 to 79 Years.SE_C01001_022
Age (Detailed Version).Total 80 to 84 Years.SE_C01001_023
Age (Detailed Version).Total 85 Years and Over.SE_C01001_024
Age (Detailed Version).Total Under 5 Years.SE_C01001_002
Age (Detailed Version).Total.SE_C01001_001
Age (Short Version).Total Population 18 to 34 Years.SE_B01001_003
Age (Short Version).Total Population 35 to 64 Years.SE_B01001_004
Age (Short Version).Total Population 65 and Over.SE_B01001_005
Age (Short Version).Total Population Under 18 Years.SE_B01001_002
Age (Short Version).Total Population.SE_B01001_001
Age - Cumulative (Less).Total Population Less than 10 Years.SE_A01001A_003
Age - Cumulative (Less).Total Population Less than 15 Years.SE_A01001A_004
Age - Cumulative (Less).Total Population Less than 18 Years.SE_A01001A_005
Age - Cumulative (Less).Total Population Less than 25 Years.SE_A01001A_006
Age - Cumulative (Less).Total Population Less than 35 Years.SE_A01001A_007
Age - Cumulative (Less).Total Population Less than 45 Years.SE_A01001A_008
Age - Cumulative (Less).Total Population Less than 5 Years.SE_A01001A_002
Age - Cumulative (Less).Total Population Less than 55 Years.SE_A01001A_009
Age - Cumulative (Less).Total Population Less than 65 Years.SE_A01001A_010
Age - Cumulative (Less).Total Population Less than 75 Years.SE_A01001A_011
Age - Cumulative (Less).Total Population Less than 85 Years.SE_A01001A_012
Age - Cumulative (Less).Total Population.SE_A01001A_001
Age - Cumulative (More).Total Population More than 10 Years.SE_A01001B_003
Age - Cumulative (More).Total Population More than 15 Years.SE_A01001B_004
Age - Cumulative (More).Total Population More than 18 Years.SE_A01001B_005
Age - Cumulative (More).Total Population More than 25 Years.SE_A01001B_006
Age - Cumulative (More).Total Population More than 35 Years.SE_A01001B_007
Age - Cumulative (More).Total Population More than 45 Years.SE_A01001B_008
Age - Cumulative (More).Total Population More than 5 Years.SE_A01001B_002
Age - Cumulative (More).Total Population More than 55 Years.SE_A01001B_009
Age - Cumulative (More).Total Population More than 65 Years.SE_A01001B_010
Age - Cumulative (More).Total Population More than 75 Years.SE_A01001B_011
Age - Cumulative (More).Total Population More than 85 Years.SE_A01001B_012
Age - Cumulative (More).Total Population.SE_A01001B_001
Age for Female Population (Short Version).Female Population 18 to 34 Years.SE_A01002A_003
Age for Female Population (Short Version).Female Population 35 to 64 Years.SE_A01002A_004
Age for Female Population (Short Version).Female Population 65 and Over.SE_A01002A_005
Age for Female Population (Short Version).Female Population Under 18 Years.SE_A01002A_002
Age for Female Population (Short Version).Female Population.SE_A01002A_001
Age for Male Population (Short Version).Male Population 18 to 34 Years.SE_A01002B_003
Age for Male Population (Short Version).Male Population 35 to 64 Years.SE_A01002B_004
Age for Male Population (Short Version).Male Population 65 and Over.SE_A01002B_005
Age for Male Population (Short Version).Male Population Under 18 Years.SE_A01002B_002
Age for Male Population (Short Version).Male Population.SE_A01002B_001
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 15 to 24 Years.SE_A01003B_002
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 25 to 34 Years.SE_A01003B_003
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 35 to 44 Years.SE_A01003B_004
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 45 to 54 Years.SE_A01003B_005
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 55 to 59 Years.SE_A01003B_006
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 60 to 64 Years.SE_A01003B_007
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 65 to 74 Years.SE_A01003B_008
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 75 to 84 Years.SE_A01003B_009
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 85 Years and Over.SE_A01003B_010
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units.SE_A01003B_001
Age.Total Population 10 to 14 Years.SE_A01001_004
Age.Total Population 15 to 17 Years.SE_A01001_005
Age.Total Population 18 to 24 Years.SE_A01001_006
Age.Total Population 25 to 34 Years.SE_A01001_007
Age.Total Population 35 to 44 Years.SE_A01001_008
Age.Total Population 45 to 54 Years.SE_A01001_009
Age.Total Population 5 to 9 Years.SE_A01001_003
Age.Total Population 55 to 64 Years.SE_A01001_010
Age.Total Population 65 to 74 Years.SE_A01001_011
Age.Total Population 75 to 84 Years.SE_A01001_012
Age.Total Population 85 Years and Over.SE_A01001_013
Age.Total Population Under 5 Years.SE_A01001_002
Age.Total Population.SE_A01001_001
Aggregate Family Income (In 2018 Inflation Adjusted Dollars).Aggregate Family Income (In 2018 Inflation Adjusted Dollars).SE_A14020_001
Aggregate Gross Rent.Aggregate Gross Rent for Specified  Renter-Occupied Housing Units.SE_A18004_001
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14019_002
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14019_001
Aggregate Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14018_001
Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over White Alone.SE_A14023_002
Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over.SE_A14023_001
Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation-Adjusted Dollars) for Population 15 Years and Over White Alone, Not Hispanic or Latino.SE_A14023_010
Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over.SE_A14022_001
Aggregate Nonfamily Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Nonfamily Household Income (In 2018 Inflation Adjusted Dollars).SE_A14021_001
Ancestry.Total Ancestry Not Specified Ancestry Not Reported.SE_A05001_007
Ancestry.Total Ancestry Not Specified Ancestry Unclassified.SE_A05001_006
Ancestry.Total Ancestry Not Specified.SE_A05001_005
Ancestry.Total Ancestry Specified Multiple Ancestry.SE_A05001_004
Ancestry.Total Ancestry Specified Single Ancestry.SE_A05001_003
Ancestry.Total Ancestry Specified.SE_A05001_002
Ancestry.Total.SE_A05001_001
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Indian.SE_A03002_002
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Bangladeshi.SE_A03002_003
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Bhutanese.SE_A03002_020
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Burmese.SE_A03002_021
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Cambodian.SE_A03002_004
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Chinese, Except Taiwanese.SE_A03002_005
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Filipino.SE_A03002_006
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Hmong.SE_A03002_007
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Indonesian.SE_A03002_008
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Japanese.SE_A03002_009
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Korean.SE_A03002_010
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Laotian.SE_A03002_011
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Malaysian.SE_A03002_012
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Mongolian.SE_A03002_022
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Nepalese.SE_A03002_023
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Okinawan.SE_A03002_024
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Other Asian, Not Specified.SE_A03002_019
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Other Asian, Specified.SE_A03002_018
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Pakistani.SE_A03002_013
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Sri Lankan.SE_A03002_014
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Taiwanese.SE_A03002_015
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Thai.SE_A03002_016
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Two or More Asian.SE_A03002_025
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Vietnamese.SE_A03002_017
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total.SE_A03002_001
Average Family Income (In 2018 Inflation Adjusted Dollars).Average Family Income (In 2018 Inflation Adjusted Dollars).SE_A14011_001
Average Gross Rent.Average Gross Rent for Renter-Occupied Housing Units.SE_A18005_001
Average Household Income (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars).SE_A14008_001
Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14009_002
Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars).SE_A14009_001
Average Household Size of Renter-Occupied Housing Units.Average Household Size for Renter-Occupied Housing Units.SE_A10003B_001
Average Household Size.Average Household Size.SE_A10003_001
Average Non-Family Income (In 2018 Inflation Adjusted Dollars).Average Nonfamily Income (In 2018 Inflation Adjusted Dollars).SE_A14013_001
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom No Cash Rent.SE_A18006_019
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $1,000 to $1,499.SE_A18006_017
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $1,500 or More.SE_A18006_018
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $300 to $499.SE_A18006_014
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $500 to $749.SE_A18006_015
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $750 to $999.SE_A18006_016
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent Less than $300.SE_A18006_013
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent.SE_A18006_012
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom.SE_A18006_011
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms No Cash Rent.SE_A18006_028
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $1,000 to $1,499.SE_A18006_026
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $1,500 or More.SE_A18006_027
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $300 to $499.SE_A18006_023
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $500 to $749.SE_A18006_024
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $750 to $999.SE_A18006_025
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent Less than $300.SE_A18006_022
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent.SE_A18006_021
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms.SE_A18006_020
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms No Cash Rent.SE_A18006_037
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $1,000 to $1,499.SE_A18006_035
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $1,500 or More.SE_A18006_036
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $300 to $499.SE_A18006_032
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $500 to $749.SE_A18006_033
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $750 to $999.SE_A18006_034
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent Less than $300.SE_A18006_031
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent.SE_A18006_030
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms.SE_A18006_029
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom No Cash Rent.SE_A18006_010
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $1,000 to $1,499.SE_A18006_008
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $1,500 or More.SE_A18006_009
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $300 to $499.SE_A18006_005
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $500 to $749.SE_A18006_006
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $750 to $999.SE_A18006_007
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent Less than $300.SE_A18006_004
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent.SE_A18006_003
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom.SE_A18006_002
Bedrooms by Gross Rent.Renter-Occupied Housing Units.SE_A18006_001
Complete Facilities (Renter-Occupied Housing Units).Renter-Occupied Housing Units Complete Kitchen Facilities.SE_A10033B_003
Complete Facilities (Renter-Occupied Housing Units).Renter-Occupied Housing Units Complete Plumbing Facilities.SE_A10033B_002
Complete Facilities (Renter-Occupied Housing Units).Renter-Occupied Housing Units.SE_A10033B_001

In [40]:
puma_migpuma = lio.load_puma_migpuma("../geometry/equivalencies/puma_migpuma_2010.csv")
puma_migpuma.head()

        State  MIGPUMA
PUMA
0100100    01  0100190
0100200    01  0100290
0100301    01  0100290
0100302    01  0100290
0100400    01  0100400

In [41]:
puma_df_numeric = puma_df.select_dtypes(include="number")
dropped = puma_df.columns.difference(puma_df.select_dtypes(include="number").columns)
print(dropped.tolist())

['File Identification.Geo_FILEID', 'Geographic Identifier.Geo_GEOID', 'Name of Area.Geo_NAME', 'Qualified Area Name.Geo_qname', 'Qualifying Name.Geo_QName', 'State/U.S.-Abbreviation (USPS).Geo_STUSAB']

In [42]:
puma_df_numeric["MIGPUMA"] = puma_migpuma.loc[puma_df_numeric.index, "MIGPUMA"]
puma_df_numeric["MIGPUMA"]

PUMA
0100100    0100190
0100200    0100290
0100301    0100290
0100302    0100290
0100400    0100400
            ...
5600100    5600100
5600200    5600200
5600300    5600300
5600400    5600400
5600500    5600500
Name: MIGPUMA, Length: 2336, dtype: object

In [43]:
weight_col = "Total Population.Total Population.SE_A00001_001"

weighted_sum_cols = [
    c for c in puma_df_numeric.columns if "Median" in c or "Average" in c
]
other_cols = [
    c for c in puma_df_numeric.columns if c not in weighted_sum_cols and c != "MIGPUMA"
]


def agg_group(group):
    # usually can just sum
    result = {col: group[col].sum() for col in other_cols}
    # for aggregate statistics, take a weighted average
    result.update(
        {
            col: np.average(group[col], weights=group[weight_col])
            for col in weighted_sum_cols
        }
    )
    return pd.Series(result)


migpuma_df = puma_df_numeric.groupby("MIGPUMA").apply(agg_group, include_groups=False)
migpuma_df.head()

,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).2.00 to 2.99.SE_C13004_003,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).3.00 to 3.99.SE_C13004_004,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).4.00 to 4.99.SE_C13004_005,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).5.00 and Over.SE_C13004_006,Aggregate Family Income (In 2018 Inflation Adjusted Dollars).Aggregate Family Income (In 2018 Inflation Adjusted Dollars).SE_A14020_001,Aggregate Gross Rent.Aggregate Gross Rent for Specified Renter-Occupied Housing Units.SE_A18004_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14019_002,Aggregate Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14018_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14019_001,...,Median Income by Sex by Work Experience (In 2018 Inflation Adjusted Dollars) (For Population Age 15+).Median Income for Population 15 Years and Over Female Other.SE_A14014_007,"Median Income by Sex by Work Experience (In 2018 Inflation Adjusted Dollars) (For Population Age 15+).Median Income for Population 15 Years and Over Female Worked Full-Time, Year-Round in the Past 12 Months.SE_A14014_006",Median Income by Sex by Work Experience (In 2018 Inflation Adjusted Dollars) (For Population Age 15+).Median Income for Population 15 Years and Over Female.SE_A14014_005,Median Income by Sex by Work Experience (In 2018 Inflation Adjusted Dollars) (For Population Age 15+).Median Income for Population 15 Years and Over Male Other.SE_A14014_004,"Median Income by Sex by Work Experience (In 2018 Inflation Adjusted Dollars) (For Population Age 15+).Median Income for Population 15 Years and Over Male Worked Full-Time, Year-Round in the Past 12 Months.SE_A14014_003",Median Income by Sex by Work Experience (In 2018 Inflation Adjusted Dollars) (For Population Age 15+).Median Income for Population 15 Years and Over Male.SE_A14014_002,Median Income by Sex by Work Experience (In 2018 Inflation Adjusted Dollars) (For Population Age 15+).Median Income for Population 15 Years and Over.SE_A14014_001,Median Nonfamily Household Income (In 2018 Inflation Adjusted Dollars).Median Nonfamily Household Income (In 2018 Inflation Adjusted Dollars).SE_A14012_001,Median House Value for All Owner-Occupied Housing Units.Median Value.SE_A10036_001,Median Year Structure Built.Median Year Structure Built.SE_A10057_001
MIGPUMA,,,,,,,,,,,,,,,,,,,,,
0100190,53617.0,43940.0,33416.0,50827.0,5.902934e+09,18469400.0,60220800.0,6.783205e+09,7.356363e+09,7.356363e+09,...,12081.241631,34213.459216,18723.363610,16799.893235,46316.796426,31194.552271,23992.719188,22355.024098,122260.006021,1978.776410
0100290,81728.0,74028.0,65170.0,161472.0,1.393221e+10,53273400.0,434355400.0,1.435536e+10,1.783981e+10,1.783981e+10,...,12849.410917,41425.061993,22063.943885,17881.037960,57435.400795,40741.624872,29661.532355,35612.030641,177615.203775,1988.892087
0100400,20418.0,15526.0,11217.0,17273.0,2.247872e+09,5911200.0,59444000.0,2.429900e+09,2.642520e+09,2.642520e+09,...,11552.000000,29585.000000,16501.000000,16881.000000,42294.000000,29656.000000,22030.000000,19562.000000,107500.000000,1983.000000
0100600,26893.0,21038.0,15722.0,33435.0,3.292696e+09,11148400.0,18863500.0,3.325720e+09,3.918489e+09,3.918489e+09,...,12451.000000,35014.000000,20796.000000,17911.000000,45994.000000,35200.000000,26886.000000,28353.000000,132500.000000,1983.000000
0100700,23592.0,10818.0,8018.0,19375.0,1.990020e+09,5155600.0,24876700.0,2.430421e+09,2.504331e+09,2.504331e+09,...,11725.000000,32836.000000,17211.000000,17910.000000,45292.000000,30687.000000,22920.000000,24483.000000,123400.000000,1984.000000

In [44]:
def median_from_binned(counts, edges):
    """
    Compute median from binned frequency data via linear interpolation.

    counts : array-like of frequencies for each bin, in order
    edges  : array-like of bin edges, length = len(counts) + 1
             e.g. bins [0-10, 10-20, 20-30] -> edges = [0, 10, 20, 30]
    """
    counts = np.array(counts, dtype=float)
    total = counts.sum()
    if total == 0:
        return np.nan

    half = total / 2
    cum = np.cumsum(counts)

    # index of the bin where the cumulative count first reaches/exceeds half
    median_bin_idx = np.searchsorted(cum, half)
    cf_before = cum[median_bin_idx - 1] if median_bin_idx > 0 else 0
    f = counts[median_bin_idx]
    L = edges[median_bin_idx]
    h = edges[median_bin_idx + 1] - L

    if f == 0:
        return L  # avoid divide-by-zero if the median bin is empty

    return L + ((half - cf_before) / f) * h


bin_cols_travel_time = [
    "Travel Time to Work for Workers 16 Years and Over (Who Did Not Work At Home).Workers 16 Years and Over Who Did Not Work At Home Less than 10 Minutes.SE_B09001_002",
    "Travel Time to Work for Workers 16 Years and Over (Who Did Not Work At Home).Workers 16 Years and Over Who Did Not Work At Home 10 to 19 Minutes.SE_B09001_003",
    "Travel Time to Work for Workers 16 Years and Over (Who Did Not Work At Home).Workers 16 Years and Over Who Did Not Work At Home 20 to 29 Minutes.SE_B09001_004",
    "Travel Time to Work for Workers 16 Years and Over (Who Did Not Work At Home).Workers 16 Years and Over Who Did Not Work At Home 30 to 39 Minutes.SE_B09001_005",
    "Travel Time to Work for Workers 16 Years and Over (Who Did Not Work At Home).Workers 16 Years and Over Who Did Not Work At Home 40 to 59 Minutes.SE_B09001_006",
    "Travel Time to Work for Workers 16 Years and Over (Who Did Not Work At Home).Workers 16 Years and Over Who Did Not Work At Home 60 to 89 Minutes.SE_B09001_007",
    "Travel Time to Work for Workers 16 Years and Over (Who Did Not Work At Home).Workers 16 Years and Over Who Did Not Work At Home 90 or More Minutes.SE_B09001_008",
]

# Bin edges — last bin is an estimate
edges_travel_time = [0, 10, 20, 30, 40, 60, 90, 120]

bin_cols_rent_pct = [
    "Gross Rent as a Percentage of Household Income in 2018.Renter-Occupied Housing Units Less than 10 Percent.SE_A18002_002",
    "Gross Rent as a Percentage of Household Income in 2018.Renter-Occupied Housing Units 10 to 29 Percent.SE_A18002_003",
    "Gross Rent as a Percentage of Household Income in 2018.Renter-Occupied Housing Units 30 to 49 Percent.SE_A18002_004",
    "Gross Rent as a Percentage of Household Income in 2018.Renter-Occupied Housing Units 50 Percent or More.SE_A18002_005",
]
# last one is an estimate
edges_rent_pct = [10, 30, 50, 75]

bin_cols_owner_cost_pct = [
    "Selected Monthly Owner Costs as a Percentage of Household Income in 2018 for Housing Units Without a Mortgage.Housing Units Without a Mortgage Less than 30 Percent.SE_A10051_002",
    "Selected Monthly Owner Costs as a Percentage of Household Income in 2018 for Housing Units Without a Mortgage.Housing Units Without a Mortgage 30 Percent or More.SE_A10051_003",
    "Selected Monthly Owner Costs as a Percentage of Household Income in 2018 for Housing Units Without a Mortgage.Housing Units Without a Mortgage 50 Percent or More.SE_A10051_004",
]
edges_owner_cost_pct = [30, 50, 75]

In [45]:
for x in sorted(migpuma_df.columns):
    print(x)

Age (Detailed Version) - Cumulative (Less).Total Less than 10 Years.SE_C01001A_003
Age (Detailed Version) - Cumulative (Less).Total Less than 15 Years.SE_C01001A_004
Age (Detailed Version) - Cumulative (Less).Total Less than 18 Years.SE_C01001A_005
Age (Detailed Version) - Cumulative (Less).Total Less than 20 Years.SE_C01001A_006
Age (Detailed Version) - Cumulative (Less).Total Less than 21 Years.SE_C01001A_007
Age (Detailed Version) - Cumulative (Less).Total Less than 22 Years.SE_C01001A_008
Age (Detailed Version) - Cumulative (Less).Total Less than 25 Years.SE_C01001A_009
Age (Detailed Version) - Cumulative (Less).Total Less than 30 Years.SE_C01001A_010
Age (Detailed Version) - Cumulative (Less).Total Less than 35 Years.SE_C01001A_011
Age (Detailed Version) - Cumulative (Less).Total Less than 40 Years.SE_C01001A_012
Age (Detailed Version) - Cumulative (Less).Total Less than 45 Years.SE_C01001A_013
Age (Detailed Version) - Cumulative (Less).Total Less than 5 Years.SE_C01001A_002
Age (Detailed Version) - Cumulative (Less).Total Less than 50 Years.SE_C01001A_014
Age (Detailed Version) - Cumulative (Less).Total Less than 55 Years.SE_C01001A_015
Age (Detailed Version) - Cumulative (Less).Total Less than 60 Years.SE_C01001A_016
Age (Detailed Version) - Cumulative (Less).Total Less than 62 Years.SE_C01001A_017
Age (Detailed Version) - Cumulative (Less).Total Less than 65 Years.SE_C01001A_018
Age (Detailed Version) - Cumulative (Less).Total Less than 67 Years.SE_C01001A_019
Age (Detailed Version) - Cumulative (Less).Total Less than 70 Years.SE_C01001A_020
Age (Detailed Version) - Cumulative (Less).Total Less than 75 Years.SE_C01001A_021
Age (Detailed Version) - Cumulative (Less).Total Less than 80 Years.SE_C01001A_022
Age (Detailed Version) - Cumulative (Less).Total Less than 85 Years.SE_C01001A_023
Age (Detailed Version) - Cumulative (Less).Total.SE_C01001A_001
Age (Detailed Version) - Cumulative (More).Total More than 10 Years.SE_C01001B_003
Age (Detailed Version) - Cumulative (More).Total More than 15 Years.SE_C01001B_004
Age (Detailed Version) - Cumulative (More).Total More than 18 Years.SE_C01001B_005
Age (Detailed Version) - Cumulative (More).Total More than 20 Years.SE_C01001B_006
Age (Detailed Version) - Cumulative (More).Total More than 21 Years.SE_C01001B_007
Age (Detailed Version) - Cumulative (More).Total More than 22 Years.SE_C01001B_008
Age (Detailed Version) - Cumulative (More).Total More than 25 Years.SE_C01001B_009
Age (Detailed Version) - Cumulative (More).Total More than 30 Years.SE_C01001B_010
Age (Detailed Version) - Cumulative (More).Total More than 35 Years.SE_C01001B_011
Age (Detailed Version) - Cumulative (More).Total More than 40 Years.SE_C01001B_012
Age (Detailed Version) - Cumulative (More).Total More than 45 Years.SE_C01001B_013
Age (Detailed Version) - Cumulative (More).Total More than 5 Years.SE_C01001B_002
Age (Detailed Version) - Cumulative (More).Total More than 50 Years.SE_C01001B_014
Age (Detailed Version) - Cumulative (More).Total More than 55 Years.SE_C01001B_015
Age (Detailed Version) - Cumulative (More).Total More than 60 Years.SE_C01001B_016
Age (Detailed Version) - Cumulative (More).Total More than 62 Years.SE_C01001B_017
Age (Detailed Version) - Cumulative (More).Total More than 65 Years.SE_C01001B_018
Age (Detailed Version) - Cumulative (More).Total More than 67 Years.SE_C01001B_019
Age (Detailed Version) - Cumulative (More).Total More than 70 Years.SE_C01001B_020
Age (Detailed Version) - Cumulative (More).Total More than 75 Years.SE_C01001B_021
Age (Detailed Version) - Cumulative (More).Total More than 80 Years.SE_C01001B_022
Age (Detailed Version) - Cumulative (More).Total More than 85 Years.SE_C01001B_023
Age (Detailed Version) - Cumulative (More).Total.SE_C01001B_001
Age (Detailed Version).Total 10 to 14 Years.SE_C01001_004
Age (Detailed Version).Total 15 to 17 Years.SE_C01001_005
Age (Detailed Version).Total 18 and 19 Years.SE_C01001_006
Age (Detailed Version).Total 20 Years.SE_C01001_007
Age (Detailed Version).Total 21 Years.SE_C01001_008
Age (Detailed Version).Total 22 to 24 Years.SE_C01001_009
Age (Detailed Version).Total 25 to 29 Years.SE_C01001_010
Age (Detailed Version).Total 30 to 34 Years.SE_C01001_011
Age (Detailed Version).Total 35 to 39 Years.SE_C01001_012
Age (Detailed Version).Total 40 to 44 Years.SE_C01001_013
Age (Detailed Version).Total 45 to 49 Years.SE_C01001_014
Age (Detailed Version).Total 5 to 9 Years.SE_C01001_003
Age (Detailed Version).Total 50 to 54 Years.SE_C01001_015
Age (Detailed Version).Total 55 to 59 Years.SE_C01001_016
Age (Detailed Version).Total 60 and 61 Years.SE_C01001_017
Age (Detailed Version).Total 62 to 64 Years.SE_C01001_018
Age (Detailed Version).Total 65 and 66 Years.SE_C01001_019
Age (Detailed Version).Total 67 to 69 Years.SE_C01001_020
Age (Detailed Version).Total 70 to 74 Years.SE_C01001_021
Age (Detailed Version).Total 75 to 79 Years.SE_C01001_022
Age (Detailed Version).Total 80 to 84 Years.SE_C01001_023
Age (Detailed Version).Total 85 Years and Over.SE_C01001_024
Age (Detailed Version).Total Under 5 Years.SE_C01001_002
Age (Detailed Version).Total.SE_C01001_001
Age (Short Version).Total Population 18 to 34 Years.SE_B01001_003
Age (Short Version).Total Population 35 to 64 Years.SE_B01001_004
Age (Short Version).Total Population 65 and Over.SE_B01001_005
Age (Short Version).Total Population Under 18 Years.SE_B01001_002
Age (Short Version).Total Population.SE_B01001_001
Age - Cumulative (Less).Total Population Less than 10 Years.SE_A01001A_003
Age - Cumulative (Less).Total Population Less than 15 Years.SE_A01001A_004
Age - Cumulative (Less).Total Population Less than 18 Years.SE_A01001A_005
Age - Cumulative (Less).Total Population Less than 25 Years.SE_A01001A_006
Age - Cumulative (Less).Total Population Less than 35 Years.SE_A01001A_007
Age - Cumulative (Less).Total Population Less than 45 Years.SE_A01001A_008
Age - Cumulative (Less).Total Population Less than 5 Years.SE_A01001A_002
Age - Cumulative (Less).Total Population Less than 55 Years.SE_A01001A_009
Age - Cumulative (Less).Total Population Less than 65 Years.SE_A01001A_010
Age - Cumulative (Less).Total Population Less than 75 Years.SE_A01001A_011
Age - Cumulative (Less).Total Population Less than 85 Years.SE_A01001A_012
Age - Cumulative (Less).Total Population.SE_A01001A_001
Age - Cumulative (More).Total Population More than 10 Years.SE_A01001B_003
Age - Cumulative (More).Total Population More than 15 Years.SE_A01001B_004
Age - Cumulative (More).Total Population More than 18 Years.SE_A01001B_005
Age - Cumulative (More).Total Population More than 25 Years.SE_A01001B_006
Age - Cumulative (More).Total Population More than 35 Years.SE_A01001B_007
Age - Cumulative (More).Total Population More than 45 Years.SE_A01001B_008
Age - Cumulative (More).Total Population More than 5 Years.SE_A01001B_002
Age - Cumulative (More).Total Population More than 55 Years.SE_A01001B_009
Age - Cumulative (More).Total Population More than 65 Years.SE_A01001B_010
Age - Cumulative (More).Total Population More than 75 Years.SE_A01001B_011
Age - Cumulative (More).Total Population More than 85 Years.SE_A01001B_012
Age - Cumulative (More).Total Population.SE_A01001B_001
Age for Female Population (Short Version).Female Population 18 to 34 Years.SE_A01002A_003
Age for Female Population (Short Version).Female Population 35 to 64 Years.SE_A01002A_004
Age for Female Population (Short Version).Female Population 65 and Over.SE_A01002A_005
Age for Female Population (Short Version).Female Population Under 18 Years.SE_A01002A_002
Age for Female Population (Short Version).Female Population.SE_A01002A_001
Age for Male Population (Short Version).Male Population 18 to 34 Years.SE_A01002B_003
Age for Male Population (Short Version).Male Population 35 to 64 Years.SE_A01002B_004
Age for Male Population (Short Version).Male Population 65 and Over.SE_A01002B_005
Age for Male Population (Short Version).Male Population Under 18 Years.SE_A01002B_002
Age for Male Population (Short Version).Male Population.SE_A01002B_001
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 15 to 24 Years.SE_A01003B_002
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 25 to 34 Years.SE_A01003B_003
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 35 to 44 Years.SE_A01003B_004
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 45 to 54 Years.SE_A01003B_005
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 55 to 59 Years.SE_A01003B_006
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 60 to 64 Years.SE_A01003B_007
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 65 to 74 Years.SE_A01003B_008
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 75 to 84 Years.SE_A01003B_009
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units Householder 85 Years and Over.SE_A01003B_010
Age of Householder (Renter-Occupied Housing Units).Renter-Occupied Housing Units.SE_A01003B_001
Age.Total Population 10 to 14 Years.SE_A01001_004
Age.Total Population 15 to 17 Years.SE_A01001_005
Age.Total Population 18 to 24 Years.SE_A01001_006
Age.Total Population 25 to 34 Years.SE_A01001_007
Age.Total Population 35 to 44 Years.SE_A01001_008
Age.Total Population 45 to 54 Years.SE_A01001_009
Age.Total Population 5 to 9 Years.SE_A01001_003
Age.Total Population 55 to 64 Years.SE_A01001_010
Age.Total Population 65 to 74 Years.SE_A01001_011
Age.Total Population 75 to 84 Years.SE_A01001_012
Age.Total Population 85 Years and Over.SE_A01001_013
Age.Total Population Under 5 Years.SE_A01001_002
Age.Total Population.SE_A01001_001
Aggregate Family Income (In 2018 Inflation Adjusted Dollars).Aggregate Family Income (In 2018 Inflation Adjusted Dollars).SE_A14020_001
Aggregate Gross Rent.Aggregate Gross Rent for Specified  Renter-Occupied Housing Units.SE_A18004_001
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14019_002
Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14019_001
Aggregate Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14018_001
Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over White Alone.SE_A14023_002
Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over.SE_A14023_001
Aggregate Income (In 2018 Inflation Adjusted Dollars) by Race for Population 15 Years and Over.Aggregate Income (In 2018 Inflation-Adjusted Dollars) for Population 15 Years and Over White Alone, Not Hispanic or Latino.SE_A14023_010
Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over.Aggregate Income (In 2018 Inflation Adjusted Dollars) for Population 15 Years and Over.SE_A14022_001
Aggregate Nonfamily Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Nonfamily Household Income (In 2018 Inflation Adjusted Dollars).SE_A14021_001
Ancestry.Total Ancestry Not Specified Ancestry Not Reported.SE_A05001_007
Ancestry.Total Ancestry Not Specified Ancestry Unclassified.SE_A05001_006
Ancestry.Total Ancestry Not Specified.SE_A05001_005
Ancestry.Total Ancestry Specified Multiple Ancestry.SE_A05001_004
Ancestry.Total Ancestry Specified Single Ancestry.SE_A05001_003
Ancestry.Total Ancestry Specified.SE_A05001_002
Ancestry.Total.SE_A05001_001
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Asian Indian.SE_A03002_002
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Bangladeshi.SE_A03002_003
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Bhutanese.SE_A03002_020
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Burmese.SE_A03002_021
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Cambodian.SE_A03002_004
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Chinese, Except Taiwanese.SE_A03002_005
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Filipino.SE_A03002_006
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Hmong.SE_A03002_007
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Indonesian.SE_A03002_008
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Japanese.SE_A03002_009
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Korean.SE_A03002_010
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Laotian.SE_A03002_011
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Malaysian.SE_A03002_012
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Mongolian.SE_A03002_022
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Nepalese.SE_A03002_023
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Okinawan.SE_A03002_024
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Other Asian, Not Specified.SE_A03002_019
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Other Asian, Specified.SE_A03002_018
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Pakistani.SE_A03002_013
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Sri Lankan.SE_A03002_014
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Taiwanese.SE_A03002_015
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Thai.SE_A03002_016
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Two or More Asian.SE_A03002_025
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total Vietnamese.SE_A03002_017
Asian by Specific Origin (Asian with One Asian Category for Selected Groups).Total.SE_A03002_001
Average Family Income (In 2018 Inflation Adjusted Dollars).Average Family Income (In 2018 Inflation Adjusted Dollars).SE_A14011_001
Average Gross Rent.Average Gross Rent for Renter-Occupied Housing Units.SE_A18005_001
Average Household Income (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars).SE_A14008_001
Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14009_002
Average Household Income by Race (In 2018 Inflation Adjusted Dollars).Average Household Income (In 2018 Inflation Adjusted Dollars).SE_A14009_001
Average Household Size of Renter-Occupied Housing Units.Average Household Size for Renter-Occupied Housing Units.SE_A10003B_001
Average Household Size.Average Household Size.SE_A10003_001
Average Non-Family Income (In 2018 Inflation Adjusted Dollars).Average Nonfamily Income (In 2018 Inflation Adjusted Dollars).SE_A14013_001
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom No Cash Rent.SE_A18006_019
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $1,000 to $1,499.SE_A18006_017
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $1,500 or More.SE_A18006_018
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $300 to $499.SE_A18006_014
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $500 to $749.SE_A18006_015
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent $750 to $999.SE_A18006_016
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent Less than $300.SE_A18006_013
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom with Cash Rent.SE_A18006_012
Bedrooms by Gross Rent.Renter-Occupied Housing Units 1 Bedroom.SE_A18006_011
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms No Cash Rent.SE_A18006_028
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $1,000 to $1,499.SE_A18006_026
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $1,500 or More.SE_A18006_027
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $300 to $499.SE_A18006_023
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $500 to $749.SE_A18006_024
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent $750 to $999.SE_A18006_025
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent Less than $300.SE_A18006_022
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms with Cash Rent.SE_A18006_021
Bedrooms by Gross Rent.Renter-Occupied Housing Units 2 Bedrooms.SE_A18006_020
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms No Cash Rent.SE_A18006_037
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $1,000 to $1,499.SE_A18006_035
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $1,500 or More.SE_A18006_036
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $300 to $499.SE_A18006_032
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $500 to $749.SE_A18006_033
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent $750 to $999.SE_A18006_034
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent Less than $300.SE_A18006_031
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms with Cash Rent.SE_A18006_030
Bedrooms by Gross Rent.Renter-Occupied Housing Units 3 or More Bedrooms.SE_A18006_029
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom No Cash Rent.SE_A18006_010
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $1,000 to $1,499.SE_A18006_008
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $1,500 or More.SE_A18006_009
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $300 to $499.SE_A18006_005
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $500 to $749.SE_A18006_006
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent $750 to $999.SE_A18006_007
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent Less than $300.SE_A18006_004
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom with Cash Rent.SE_A18006_003
Bedrooms by Gross Rent.Renter-Occupied Housing Units No Bedroom.SE_A18006_002
Bedrooms by Gross Rent.Renter-Occupied Housing Units.SE_A18006_001
Complete Facilities (Renter-Occupied Housing Units).Renter-Occupied Housing Units Complete Kitchen Facilities.SE_A10033B_003
Complete Facilities (Renter-Occupied Housing Units).Renter-Occupied Housing Units Complete Plumbing Facilities.SE_A10033B_002
Complete Facilities (Renter-Occupied Housing Units).Renter-Occupied Housing Units.SE_A10033B_001

In [ ]:
for table in [migpuma_df, puma_df]:
    table["Unemployment rate"] = (
        table[
            "Unemployment Rate for Civilian Population in Labor Force 16 Years and Over.Civilian Population in Labor Force 16 Years and Over Unemployed.SE_A17005_003"
        ]
        / table[
            "Unemployment Rate for Civilian Population in Labor Force 16 Years and Over.Civilian Population in Labor Force 16 Years and Over.SE_A17005_001"
        ]
    )
    table[
        "Unemployment Rate for Civilian Population in Labor Force 16 Years and Over.Civilian Population in Labor Force 16 Years and Over Unemployed.SE_A17005_003"
    ]
    table["Proportion of people in college"] = (
        table[
            "Level of School by Type of School for Enrolled in School Population 3 Years and Over.Population 3 Years and Over Enrolled in School Private School College.SE_A12006_011"
        ]
        + table[
            "Level of School by Type of School for Enrolled in School Population 3 Years and Over.Population 3 Years and Over Enrolled in School Public School College.SE_A12006_006"
        ]
    ) / table["Total Population.Total Population.SE_A00001_001"]
    table["House vacancy proportion"] = (
        table["Occupancy Status.Housing Units Vacant.SE_A10044_003"]
        / table["Occupancy Status.Housing Units.SE_A10044_001"]
    )

    table["Median travel time"] = table[bin_cols_travel_time].apply(
        lambda row: median_from_binned(row.values, edges_travel_time), axis=1
    )
    table["Median gross rent as a percentage of household income"] = table[
        bin_cols_rent_pct
    ].apply(lambda row: median_from_binned(row.values, edges_rent_pct), axis=1)

    table["Median selected monthly owner costs as percentage of household income"] = (
        table[bin_cols_owner_cost_pct].apply(
            lambda row: median_from_binned(row.values, edges_owner_cost_pct), axis=1
        )
    )
    table["Median house value over median household income"] = (
        table[
            "Median House Value for All Owner-Occupied Housing Units.Median Value.SE_A10036_001"
        ]
        / table[
            "Median Household Income (In 2018 Inflation Adjusted Dollars).Median Household Income (In 2018 Inflation Adjusted Dollars).SE_A14006_001"
        ]
    )

    table["Proportion of people White"] = (
        table["Total Population Not Hispanic or Latino White Alone.SE_B04001_003"]
        / table["Total Population.SE_B04001_001"]
    )
    table["Proportion of people Asian"] = (
        table["Total Population Not Hispanic or Latino Asian Alone.SE_B04001_006"]
        / table["Total Population.SE_B04001_001"]
    )
    table["Proportion of people PI"] = (
        table[
            "Total Population Not Hispanic or Latino Native Hawaiian and Other Pacific Islander Alone.SE_B04001_007"
        ]
        / table["Total Population.SE_B04001_001"]
    )
    table["Proportion of people AAPI"] = (
        table["Total Population Not Hispanic or Latino Asian Alone.SE_B04001_006"]
        + table[
            "Total Population Not Hispanic or Latino Native Hawaiian and Other Pacific Islander Alone.SE_B04001_007"
        ]
    ) / table["Total Population.SE_B04001_001"]
    table["Proportion of people Black"] = (
        table[
            "Total Population Not Hispanic or Latino Black or African American Alone.SE_B04001_004"
        ]
        / table["Total Population.SE_B04001_001"]
    )
    table["Proportion of people Latino"] = (
        table["Total Population Hispanic or Latino.SE_B04001_010"]
        / table["Total Population.SE_B04001_001"]
    )
    table["Proportion of people Indian"] = (
        table[
            "Total Population Not Hispanic or Latino American Indian and Alaska Native Alone.SE_B04001_005"
        ]
        / table["Total Population.SE_B04001_001"]
    )

    table["Proportion of people other race"] = (
        table[
            "Total Population Not Hispanic or Latino Some Other Race Alone.SE_B04001_008"
        ]
        + table[
            "Total Population Not Hispanic or Latino Two or More Races.SE_B04001_009"
        ]
    ) / table["Total Population.SE_B04001_001"]

    table["Proportion of people struggling"] = (
        table[
            "Ratio of Income in 2018 to Poverty Level (Summarized).Population for Whom Poverty Status Is Determined Under 2.00 (Poor or Struggling).SE_B13004_004"
        ]
        / table[
            "Ratio of Income in 2018 to Poverty Level (Summarized).Population for Whom Poverty Status Is Determined.SE_B13004_001"
        ]
    )
    table["Years since median structure built"] = (
        year
        - table["Median Year Structure Built.Median Year Structure Built.SE_A10057_001"]
    )
    table["Proportion foreign born"] = (
        table[
            "Nativity by Citizenship Status.Total Population Foreign Born.SE_A06001_003"
        ]
        / table["Nativity by Citizenship Status.Total Population.SE_A06001_001"]
    )

    table["Proportion alternative commute"] = (
        table[
            "Means of Transportation to Work (Renter-Occupied Housing Units).Workers 16 Years and Over in Households Householder Lived in Renter-Occupied Housing Units Public Transportation (Excluding Taxicab).SE_A09004B_004"
        ]
        + table[
            "Means of Transportation to Work (Renter-Occupied Housing Units).Workers 16 Years and Over in Households Householder Lived in Renter-Occupied Housing Units Walked.SE_A09004B_005"
        ]
    ) / table[
        "Means of Transportation to Work (Renter-Occupied Housing Units).Workers 16 Years and Over in Households.SE_A09004B_008"
    ]
    table["Proportion WFH"] = (
        table[
            "Means of Transportation to Work (Renter-Occupied Housing Units).Workers 16 Years and Over in Households Householder Lived in Renter-Occupied Housing Units Worked At Home.SE_A09004B_007"
        ]
        / table[
            "Means of Transportation to Work (Renter-Occupied Housing Units).Workers 16 Years and Over in Households.SE_A09004B_008"
        ]
    )

    table["Proportion of households with children"] = (
        table[
            "Housing Units by Families and Presence of Own Children.Occupied Housing Units with Related Children of the Householder Under 18.SE_A10022_002"
        ]
        / table[
            "Housing Units by Families and Presence of Own Children.Occupied Housing Units.SE_A10022_001"
        ]
    )
    table["Labor force participation rate"] = (
        table[
            "Employment Status for Total Population 16 Years and Over.Population 16 Years and Over in Labor Force.SE_A17002_002"
        ]
        / (
            table[
                "Employment Status for Total Population 16 Years and Over.Population 16 Years and Over.SE_A17002_001"
            ]
        )
    )
    table["Proportion of people in military"] = (
        table[
            "Labor Force for Population 16 Years and Over.In Labor Force 16 Years and Over in Armed Forces.SE_A17001_002"
        ]
        / table[
            "Labor Force for Population 16 Years and Over.In Labor Force 16 Years and Over.SE_A17001_001"
        ]
    )

    table["Proportion of people 18-34"] = (
        table["Age (Short Version).Total Population 18 to 34 Years.SE_B01001_003"]
        / table["Age (Short Version).Total Population.SE_B01001_001"]
    )
    table["Proportion of people 35-64"] = (
        table["Age (Short Version).Total Population 35 to 64 Years.SE_B01001_004"]
        / table["Age (Short Version).Total Population.SE_B01001_001"]
    )
    table["Proportion of people 65+"] = (
        table["Age (Short Version).Total Population 65 and Over.SE_B01001_005"]
        / table["Age (Short Version).Total Population.SE_B01001_001"]
    )
    table["Proportion of people under 18"] = (
        table["Age (Short Version).Total Population Under 18 Years.SE_B01001_002"]
        / table["Age (Short Version).Total Population.SE_B01001_001"]
    )

    table["Proportion of people receiving public assistance income"] = (
        table[
            "Households with Public Assistance Income.Households with Public Assistance Income.SE_A10014_002"
        ]
        / table["Households with Public Assistance Income.Households.SE_A10014_001"]
    )
    table["Median household income in tens of thousands of dollars"] = (
        table[
            "Median Household Income (In 2018 Inflation Adjusted Dollars).Median Household Income (In 2018 Inflation Adjusted Dollars).SE_A14006_001"
        ]
        / 10_000
    )
    table["Median house cost in hundreds of thousands of dollars"] = (
        table[
            "Median House Value for All Owner-Occupied Housing Units.Median Value.SE_A10036_001"
        ]
        / 100_000
    )
    table["Median gross rent in thousands of dollars"] = (
        table["Median Gross Rent.Median Gross Rent.SE_A18009_001"] / 1_000
    )
    table["Median earnings in tens of thousands of dollars"] = (
        table[
            "Median Earnings by Sex by Educational Attainment in the past 12 months (In 2018 Inflation Adjusted Dollars) (For Population Age 25+).Median Earnings.SE_A15001_001"
        ]
        / 10_000
    )
    table["TOT_POP"] = table["Total Population.Total Population.SE_A00001_001"]

In [47]:
migpuma_df.to_csv(f"acs_migpuma_{year}.csv")
puma_df.to_csv(f"acs_puma_{year}.csv")