In [ ]:
import pandas as pd

In [67]:
year = 2018

In [68]:
acs_puma = pd.read_csv(f"ACS/ACS_PUMA_{year}.csv").set_index("PUMA")
acs_puma

,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).2.00 to 2.99.SE_C13004_003,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).3.00 to 3.99.SE_C13004_004,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).4.00 to 4.99.SE_C13004_005,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).5.00 and Over.SE_C13004_006,Aggregate Family Income (In 2018 Inflation Adjusted Dollars).Aggregate Family Income (In 2018 Inflation Adjusted Dollars).SE_A14020_001,Aggregate Gross Rent.Aggregate Gross Rent for Specified Renter-Occupied Housing Units.SE_A18004_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14019_002,Aggregate Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14018_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14019_001,...,Proportion of People PI,Proportion of People Black,Proportion of People Latino,Proportion of People Indian,Proportion of People Struggling,Years Since Median Structure Built,Proportion Foreign Born,Proportion Alternative Commute,Proportion WFH,Proportion of Households with Children
PUMA,,,,,,,,,,,,,,,,,,,,,
100100,31933.0,29388.0,21017.0,34097.0,3.920469e+09,13218500,32758100.0,4.345609e+09,4.782983e+09,4.782983e+09,...,0.000484,0.102615,0.049581,0.005399,0.360683,40,0.032879,0.007044,0.001910,0.287667
100200,30261.0,29524.0,22337.0,62089.0,4.835799e+09,11300600,179738000.0,4.835212e+09,6.076529e+09,6.076529e+09,...,0.000480,0.166202,0.043650,0.008846,0.253075,23,0.030714,0.000667,0.001877,0.327339
100301,19059.0,14234.0,16668.0,41579.0,3.501398e+09,19883800,99838800.0,3.228685e+09,4.620993e+09,4.620993e+09,...,0.000844,0.356812,0.053752,0.004372,0.297629,28,0.069949,0.001699,0.024352,0.270829
100302,13717.0,12171.0,8558.0,30159.0,2.576703e+09,14032800,122376300.0,2.996072e+09,3.540721e+09,3.540721e+09,...,0.000637,0.192634,0.067723,0.002656,0.326027,45,0.062740,0.018630,0.007438,0.275846
100400,20418.0,15526.0,11217.0,17273.0,2.247872e+09,5911200,59444000.0,2.429900e+09,2.642520e+09,2.642520e+09,...,0.001427,0.022532,0.095098,0.011801,0.468761,35,0.049407,0.004407,0.004137,0.329190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5600100,22353.0,20498.0,13697.0,34304.0,3.537248e+09,13092600,37803700.0,4.585974e+09,4.740338e+09,4.740338e+09,...,0.000530,0.004200,0.072526,0.007144,0.231175,35,0.046287,0.046177,0.012275,0.247215
5600200,19065.0,13663.0,13071.0,24642.0,2.197435e+09,7321100,55545000.0,2.752056e+09,2.811060e+09,2.811060e+09,...,0.000000,0.002369,0.075874,0.011120,0.248445,35,0.014667,0.023111,0.007992,0.307398
5600300,23400.0,16650.0,20580.0,35230.0,3.173642e+09,17013600,93906000.0,3.898010e+09,4.297310e+09,4.297310e+09,...,0.000884,0.019618,0.130624,0.007025,0.280374,40,0.039512,0.050289,0.007021,0.245761
5600400,19903.0,15137.0,12752.0,30036.0,2.780284e+09,9704500,96802900.0,3.509874e+09,3.730858e+09,3.730858e+09,...,0.000472,0.010665,0.096481,0.009238,0.270761,42,0.014503,0.009755,0.024380,0.297689
5600500,22399.0,14234.0,11300.0,28803.0,2.585916e+09,8450100,81265200.0,3.015096e+09,3.286162e+09,3.286162e+09,...,0.001691,0.004948,0.105138,0.073581,0.312056,38,0.030944,0.021361,0.006232,0.291648

In [69]:
acs_migpuma = pd.read_csv(f"ACS/ACS_MIGPUMA_{year}.csv").set_index("MIGPUMA")
acs_migpuma

,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).2.00 to 2.99.SE_C13004_003,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).3.00 to 3.99.SE_C13004_004,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).4.00 to 4.99.SE_C13004_005,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).5.00 and Over.SE_C13004_006,Aggregate Family Income (In 2018 Inflation Adjusted Dollars).Aggregate Family Income (In 2018 Inflation Adjusted Dollars).SE_A14020_001,Aggregate Gross Rent.Aggregate Gross Rent for Specified Renter-Occupied Housing Units.SE_A18004_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14019_002,Aggregate Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14018_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14019_001,...,Proportion of People PI,Proportion of People Black,Proportion of People Latino,Proportion of People Indian,Proportion of People Struggling,Years Since Median Structure Built,Proportion Foreign Born,Proportion Alternative Commute,Proportion WFH,Proportion of Households with Children
MIGPUMA,,,,,,,,,,,,,,,,,,,,,
100190,53617.0,43940.0,33416.0,50827.0,5.902934e+09,18469400.0,60220800.0,6.783205e+09,7.356363e+09,7.356363e+09,...,0.000316,0.090577,0.039177,0.003689,0.389029,39.223590,0.024009,0.006143,0.002118,0.281883
100290,81728.0,74028.0,65170.0,161472.0,1.393221e+10,53273400.0,434355400.0,1.435536e+10,1.783981e+10,1.783981e+10,...,0.000647,0.183514,0.065476,0.005501,0.297903,29.107913,0.051891,0.004903,0.010434,0.298777
100400,20418.0,15526.0,11217.0,17273.0,2.247872e+09,5911200.0,59444000.0,2.429900e+09,2.642520e+09,2.642520e+09,...,0.001427,0.022532,0.095098,0.011801,0.468761,35.000000,0.049407,0.004407,0.004137,0.329190
100600,26893.0,21038.0,15722.0,33435.0,3.292696e+09,11148400.0,18863500.0,3.325720e+09,3.918489e+09,3.918489e+09,...,0.000473,0.123157,0.068276,0.017013,0.353630,35.000000,0.033418,0.006641,0.000000,0.313499
100700,23592.0,10818.0,8018.0,19375.0,1.990020e+09,5155600.0,24876700.0,2.430421e+09,2.504331e+09,2.504331e+09,...,0.000085,0.009832,0.040278,0.004153,0.414206,34.000000,0.015901,0.001531,0.004713,0.325130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5600100,22353.0,20498.0,13697.0,34304.0,3.537248e+09,13092600.0,37803700.0,4.585974e+09,4.740338e+09,4.740338e+09,...,0.000530,0.004200,0.072526,0.007144,0.231175,35.000000,0.046287,0.046177,0.012275,0.247215
5600200,19065.0,13663.0,13071.0,24642.0,2.197435e+09,7321100.0,55545000.0,2.752056e+09,2.811060e+09,2.811060e+09,...,0.000000,0.002369,0.075874,0.011120,0.248445,35.000000,0.014667,0.023111,0.007992,0.307398
5600300,23400.0,16650.0,20580.0,35230.0,3.173642e+09,17013600.0,93906000.0,3.898010e+09,4.297310e+09,4.297310e+09,...,0.000884,0.019618,0.130624,0.007025,0.280374,40.000000,0.039512,0.050289,0.007021,0.245761
5600400,19903.0,15137.0,12752.0,30036.0,2.780284e+09,9704500.0,96802900.0,3.509874e+09,3.730858e+09,3.730858e+09,...,0.000472,0.010665,0.096481,0.009238,0.270761,42.000000,0.014503,0.009755,0.024380,0.297689
5600500,22399.0,14234.0,11300.0,28803.0,2.585916e+09,8450100.0,81265200.0,3.015096e+09,3.286162e+09,3.286162e+09,...,0.001691,0.004948,0.105138,0.073581,0.312056,38.000000,0.030944,0.021361,0.006232,0.291648

In [70]:
lodes_puma = pd.read_csv(f"lodes/wac_puma_{year}.csv").set_index("PUMA")
lodes_puma

,Total number of jobs,Number of jobs for workers age 29 or younger,Number of jobs for workers age 30 to 54,Number of jobs for workers age 55 or older,Number of jobs with earnings $1250/month or less,Number of jobs with earnings $1251/month to $3333/month,Number of jobs with earnings greater than $3333/month,"Number of jobs in NAICS sector 11 (Agriculture, Forestry, Fishing and Hunting)","Number of jobs in NAICS sector 21 (Mining, Quarrying, and Oil and Gas Extraction)",Number of jobs in NAICS sector 22 (Utilities),...,Number of jobs in NAICS sector 61 (Educational Services),Number of jobs in NAICS sector 62 (Health Care and Social Assistance),"Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)",Number of jobs in NAICS sector 72 (Accommodation and Food Services),Number of jobs in NAICS sector 81 (Other Services [except Public Administration]),Number of jobs in NAICS sector 92 (Public Administration),Number of jobs for workers with Educational Attainment: Less than high school,"Number of jobs for workers with Educational Attainment: High school or equivalent, no college",Number of jobs for workers with Educational Attainment: Some college or Associate degree,Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree
PUMA,,,,,,,,,,,,,,,,,,,,,
100100,65126,17136,33682,14308,16098,26779,22249,327,187,667,...,5244,8385,547,6459,1295,3035,6271,15596,15924,10199
100200,55849,12289,30305,13255,11232,16446,28171,589,18,336,...,6750,3403,888,4140,860,3363,4811,12422,13334,12993
100301,78929,19094,42045,17790,17004,20970,40955,164,74,81,...,4888,4724,1140,8349,1240,747,6405,15300,18471,19659
100302,73792,18404,39227,16161,19130,26425,28237,13,0,610,...,3284,18803,1187,6280,1788,3981,6420,15549,18625,14794
100400,38349,9478,20490,8381,8663,17262,12424,339,20,471,...,3249,4185,103,2904,536,1831,4218,10119,9416,5118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5600100,54624,11754,29036,13834,14569,17808,22247,882,1574,370,...,5316,8056,1740,9497,1628,3025,4896,12946,14447,10581
5600200,45443,8889,24613,11941,9694,13269,22480,615,6767,873,...,4983,5484,335,3835,1408,3810,3921,12436,12994,7203
5600300,63021,15408,32819,14794,14940,20399,27682,499,791,227,...,8711,9714,682,6383,1698,7672,5195,13416,16437,12565
5600400,53153,11890,28441,12822,11754,16371,25028,526,4880,467,...,4856,7425,838,5363,1792,3215,4663,13825,14622,8153
5600500,52023,10586,28254,13183,11987,15653,24383,378,6601,764,...,6529,6784,465,5267,1223,4338,4640,13677,14717,8403

In [71]:
lodes_migpuma = pd.read_csv(f"lodes/wac_migpuma_{year}.csv").set_index("MIGPUMA")
lodes_migpuma

,Total number of jobs,Number of jobs for workers age 29 or younger,Number of jobs for workers age 30 to 54,Number of jobs for workers age 55 or older,Number of jobs with earnings $1250/month or less,Number of jobs with earnings $1251/month to $3333/month,Number of jobs with earnings greater than $3333/month,"Number of jobs in NAICS sector 11 (Agriculture, Forestry, Fishing and Hunting)","Number of jobs in NAICS sector 21 (Mining, Quarrying, and Oil and Gas Extraction)",Number of jobs in NAICS sector 22 (Utilities),...,Number of jobs in NAICS sector 61 (Educational Services),Number of jobs in NAICS sector 62 (Health Care and Social Assistance),"Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)",Number of jobs in NAICS sector 72 (Accommodation and Food Services),Number of jobs in NAICS sector 81 (Other Services [except Public Administration]),Number of jobs in NAICS sector 92 (Public Administration),Number of jobs for workers with Educational Attainment: Less than high school,"Number of jobs for workers with Educational Attainment: High school or equivalent, no college",Number of jobs for workers with Educational Attainment: Some college or Associate degree,Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree
MIGPUMA,,,,,,,,,,,,,,,,,,,,,
100190,98779,25260,51315,22204,24429,40764,33586,804,496,1136,...,8442,14392,673,9445,2087,4809,9425,24176,24604,15314
100290,251113,61138,133922,56053,57381,83406,110326,978,110,1439,...,17880,31247,3529,22888,4706,9503,22517,53389,60427,53642
100400,38349,9478,20490,8381,8663,17262,12424,339,20,471,...,3249,4185,103,2904,536,1831,4218,10119,9416,5118
100600,55347,12855,30219,12273,12340,20116,22891,224,68,430,...,3955,6304,283,4922,1059,2021,5588,13943,14067,8894
100700,37022,9531,19312,8179,8457,16222,12343,483,14,277,...,2931,4713,190,3076,679,1777,3639,9418,9358,5076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5600100,54624,11754,29036,13834,14569,17808,22247,882,1574,370,...,5316,8056,1740,9497,1628,3025,4896,12946,14447,10581
5600200,45443,8889,24613,11941,9694,13269,22480,615,6767,873,...,4983,5484,335,3835,1408,3810,3921,12436,12994,7203
5600300,63021,15408,32819,14794,14940,20399,27682,499,791,227,...,8711,9714,682,6383,1698,7672,5195,13416,16437,12565
5600400,53153,11890,28441,12822,11754,16371,25028,526,4880,467,...,4856,7425,838,5363,1792,3215,4663,13825,14622,8153
5600500,52023,10586,28254,13183,11987,15653,24383,378,6601,764,...,6529,6784,465,5267,1223,4338,4640,13677,14717,8403

In [72]:
pumas = acs_puma.join(lodes_puma)
pumas

,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).2.00 to 2.99.SE_C13004_003,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).3.00 to 3.99.SE_C13004_004,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).4.00 to 4.99.SE_C13004_005,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).5.00 and Over.SE_C13004_006,Aggregate Family Income (In 2018 Inflation Adjusted Dollars).Aggregate Family Income (In 2018 Inflation Adjusted Dollars).SE_A14020_001,Aggregate Gross Rent.Aggregate Gross Rent for Specified Renter-Occupied Housing Units.SE_A18004_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14019_002,Aggregate Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14018_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14019_001,...,Number of jobs in NAICS sector 61 (Educational Services),Number of jobs in NAICS sector 62 (Health Care and Social Assistance),"Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)",Number of jobs in NAICS sector 72 (Accommodation and Food Services),Number of jobs in NAICS sector 81 (Other Services [except Public Administration]),Number of jobs in NAICS sector 92 (Public Administration),Number of jobs for workers with Educational Attainment: Less than high school,"Number of jobs for workers with Educational Attainment: High school or equivalent, no college",Number of jobs for workers with Educational Attainment: Some college or Associate degree,Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree
PUMA,,,,,,,,,,,,,,,,,,,,,
100100,31933.0,29388.0,21017.0,34097.0,3.920469e+09,13218500,32758100.0,4.345609e+09,4.782983e+09,4.782983e+09,...,5244,8385,547,6459,1295,3035,6271,15596,15924,10199
100200,30261.0,29524.0,22337.0,62089.0,4.835799e+09,11300600,179738000.0,4.835212e+09,6.076529e+09,6.076529e+09,...,6750,3403,888,4140,860,3363,4811,12422,13334,12993
100301,19059.0,14234.0,16668.0,41579.0,3.501398e+09,19883800,99838800.0,3.228685e+09,4.620993e+09,4.620993e+09,...,4888,4724,1140,8349,1240,747,6405,15300,18471,19659
100302,13717.0,12171.0,8558.0,30159.0,2.576703e+09,14032800,122376300.0,2.996072e+09,3.540721e+09,3.540721e+09,...,3284,18803,1187,6280,1788,3981,6420,15549,18625,14794
100400,20418.0,15526.0,11217.0,17273.0,2.247872e+09,5911200,59444000.0,2.429900e+09,2.642520e+09,2.642520e+09,...,3249,4185,103,2904,536,1831,4218,10119,9416,5118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5600100,22353.0,20498.0,13697.0,34304.0,3.537248e+09,13092600,37803700.0,4.585974e+09,4.740338e+09,4.740338e+09,...,5316,8056,1740,9497,1628,3025,4896,12946,14447,10581
5600200,19065.0,13663.0,13071.0,24642.0,2.197435e+09,7321100,55545000.0,2.752056e+09,2.811060e+09,2.811060e+09,...,4983,5484,335,3835,1408,3810,3921,12436,12994,7203
5600300,23400.0,16650.0,20580.0,35230.0,3.173642e+09,17013600,93906000.0,3.898010e+09,4.297310e+09,4.297310e+09,...,8711,9714,682,6383,1698,7672,5195,13416,16437,12565
5600400,19903.0,15137.0,12752.0,30036.0,2.780284e+09,9704500,96802900.0,3.509874e+09,3.730858e+09,3.730858e+09,...,4856,7425,838,5363,1792,3215,4663,13825,14622,8153
5600500,22399.0,14234.0,11300.0,28803.0,2.585916e+09,8450100,81265200.0,3.015096e+09,3.286162e+09,3.286162e+09,...,6529,6784,465,5267,1223,4338,4640,13677,14717,8403

In [73]:
migpumas = acs_migpuma.join(lodes_migpuma)
migpumas

,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).2.00 to 2.99.SE_C13004_003,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).3.00 to 3.99.SE_C13004_004,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).4.00 to 4.99.SE_C13004_005,Ratio of Income in 2018 to Poverty Level (Summarized - top-coded at 5.00).5.00 and Over.SE_C13004_006,Aggregate Family Income (In 2018 Inflation Adjusted Dollars).Aggregate Family Income (In 2018 Inflation Adjusted Dollars).SE_A14020_001,Aggregate Gross Rent.Aggregate Gross Rent for Specified Renter-Occupied Housing Units.SE_A18004_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) Two or More Races Householder.SE_A14019_008,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars) White Alone Householder.SE_A14019_002,Aggregate Household Income (In 2018 Inflation Adjusted Dollars).Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14018_001,Aggregate Household Income (In 2018 Inflation Adjusted Dollars) by Race.Aggregate Household Income (In 2018 Inflation Adjusted Dollars).SE_A14019_001,...,Number of jobs in NAICS sector 61 (Educational Services),Number of jobs in NAICS sector 62 (Health Care and Social Assistance),"Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)",Number of jobs in NAICS sector 72 (Accommodation and Food Services),Number of jobs in NAICS sector 81 (Other Services [except Public Administration]),Number of jobs in NAICS sector 92 (Public Administration),Number of jobs for workers with Educational Attainment: Less than high school,"Number of jobs for workers with Educational Attainment: High school or equivalent, no college",Number of jobs for workers with Educational Attainment: Some college or Associate degree,Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree
MIGPUMA,,,,,,,,,,,,,,,,,,,,,
100190,53617.0,43940.0,33416.0,50827.0,5.902934e+09,18469400.0,60220800.0,6.783205e+09,7.356363e+09,7.356363e+09,...,8442,14392,673,9445,2087,4809,9425,24176,24604,15314
100290,81728.0,74028.0,65170.0,161472.0,1.393221e+10,53273400.0,434355400.0,1.435536e+10,1.783981e+10,1.783981e+10,...,17880,31247,3529,22888,4706,9503,22517,53389,60427,53642
100400,20418.0,15526.0,11217.0,17273.0,2.247872e+09,5911200.0,59444000.0,2.429900e+09,2.642520e+09,2.642520e+09,...,3249,4185,103,2904,536,1831,4218,10119,9416,5118
100600,26893.0,21038.0,15722.0,33435.0,3.292696e+09,11148400.0,18863500.0,3.325720e+09,3.918489e+09,3.918489e+09,...,3955,6304,283,4922,1059,2021,5588,13943,14067,8894
100700,23592.0,10818.0,8018.0,19375.0,1.990020e+09,5155600.0,24876700.0,2.430421e+09,2.504331e+09,2.504331e+09,...,2931,4713,190,3076,679,1777,3639,9418,9358,5076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5600100,22353.0,20498.0,13697.0,34304.0,3.537248e+09,13092600.0,37803700.0,4.585974e+09,4.740338e+09,4.740338e+09,...,5316,8056,1740,9497,1628,3025,4896,12946,14447,10581
5600200,19065.0,13663.0,13071.0,24642.0,2.197435e+09,7321100.0,55545000.0,2.752056e+09,2.811060e+09,2.811060e+09,...,4983,5484,335,3835,1408,3810,3921,12436,12994,7203
5600300,23400.0,16650.0,20580.0,35230.0,3.173642e+09,17013600.0,93906000.0,3.898010e+09,4.297310e+09,4.297310e+09,...,8711,9714,682,6383,1698,7672,5195,13416,16437,12565
5600400,19903.0,15137.0,12752.0,30036.0,2.780284e+09,9704500.0,96802900.0,3.509874e+09,3.730858e+09,3.730858e+09,...,4856,7425,838,5363,1792,3215,4663,13825,14622,8153
5600500,22399.0,14234.0,11300.0,28803.0,2.585916e+09,8450100.0,81265200.0,3.015096e+09,3.286162e+09,3.286162e+09,...,6529,6784,465,5267,1223,4338,4640,13677,14717,8403

In [74]:
for df in [pumas, migpumas]:
    total_jobs = df["Total number of jobs"]

    df["Proportion of jobs for ages 29 and younger"] = (
        df["Number of jobs for workers age 29 or younger"] / total_jobs
    )
    df["Proportion of jobs for ages 30 to 54"] = (
        df["Number of jobs for workers age 30 to 54"] / total_jobs
    )
    df["Proportion of jobs for ages 55 and older"] = (
        df["Number of jobs for workers age 55 or older"] / total_jobs
    )

    df["Proportion of jobs paying 1250 a month or less"] = (
        df["Number of jobs with earnings $1250/month or less"] / total_jobs
    )
    df["Proportion of jobs paying 1251 to 3333 a month or less"] = (
        df["Number of jobs with earnings $1251/month to $3333/month"] / total_jobs
    )
    df["Proportion of jobs paying more than 3333 a month"] = (
        df["Number of jobs with earnings greater than $3333/month"] / total_jobs
    )
    df["Proportion of agriculture jobs"] = (
        df[
            "Number of jobs in NAICS sector 11 (Agriculture, Forestry, Fishing and Hunting)"
        ]
        / total_jobs
    )
    df["Proportion of extraction jobs"] = (
        df[
            "Number of jobs in NAICS sector 21 (Mining, Quarrying, and Oil and Gas Extraction)"
        ]
        / total_jobs
    )

    df["Proportion of utilities jobs"] = (
        df["Number of jobs in NAICS sector 22 (Utilities)"] / total_jobs
    )

    df["Proportion of construction jobs"] = (
        df["Number of jobs in NAICS sector 23 (Construction)"] / total_jobs
    )

    df["Proportion of manufacturing jobs"] = (
        df["Number of jobs in NAICS sector 31-33 (Manufacturing)"] / total_jobs
    )

    df["Proportion of wholesale trade jobs"] = (
        df["Number of jobs in NAICS sector 42 (Wholesale Trade)"] / total_jobs
    )

    df["Proportion of retail trade jobs"] = (
        df["Number of jobs in NAICS sector 44-45 (Retail Trade)"] / total_jobs
    )

    df["Proportion of transportation jobs"] = (
        df["Number of jobs in NAICS sector 48-49 (Transportation and Warehousing)"]
        / total_jobs
    )

    df["Proportion of information jobs"] = (
        df["Number of jobs in NAICS sector 51 (Information)"] / total_jobs
    )

    df["Proportion of finance jobs"] = (
        df["Number of jobs in NAICS sector 52 (Finance and Insurance)"] / total_jobs
    )

    df["Proportion of real estate jobs"] = (
        df["Number of jobs in NAICS sector 53 (Real Estate and Rental and Leasing)"]
        / total_jobs
    )

    df["Proportion of professional jobs"] = (
        df[
            "Number of jobs in NAICS sector 54 (Professional, Scientific, and Technical Services)"
        ]
        / total_jobs
    )

    df["Proportion of management jobs"] = (
        df[
            "Number of jobs in NAICS sector 55 (Management of Companies and Enterprises)"
        ]
        / total_jobs
    )

    df["Proportion of support/administrative jobs"] = (
        df[
            "Number of jobs in NAICS sector 56 (Administrative and Support and Waste Management and Remediation Services)"
        ]
        / total_jobs
    )

    df["Proportion of educational jobs"] = (
        df["Number of jobs in NAICS sector 61 (Educational Services)"] / total_jobs
    )

    df["Proportion of health jobs"] = (
        df["Number of jobs in NAICS sector 62 (Health Care and Social Assistance)"]
        / total_jobs
    )

    df["Proportion of entertainment jobs"] = (
        df["Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)"]
        / total_jobs
    )

    df["Proportion of hospitality jobs"] = (
        df["Number of jobs in NAICS sector 72 (Accommodation and Food Services)"]
        / total_jobs
    )

    df["Proportion of other services jobs"] = (
        df[
            "Number of jobs in NAICS sector 81 (Other Services [except Public Administration])"
        ]
        / total_jobs
    )

    df["Proportion of public administration jobs"] = (
        df["Number of jobs in NAICS sector 92 (Public Administration)"] / total_jobs
    )

    total_jobs_by_education = (
        df[
            "Number of jobs for workers with Educational Attainment: Less than high school"
        ]
        + df[
            "Number of jobs for workers with Educational Attainment: High school or equivalent, no college"
        ]
        + df[
            "Number of jobs for workers with Educational Attainment: Some college or Associate degree"
        ]
        + df[
            "Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree"
        ]
    )

    df["Proportion of jobs with less than high school education"] = (
        df[
            "Number of jobs for workers with Educational Attainment: Less than high school"
        ]
        / total_jobs_by_education
    )

    df["Proportion of jobs with high school education, no college"] = (
        df[
            "Number of jobs for workers with Educational Attainment: High school or equivalent, no college"
        ]
        / total_jobs_by_education
    )

    df["Proportion of jobs with some college or associate degree"] = (
        df[
            "Number of jobs for workers with Educational Attainment: Some college or Associate degree"
        ]
        / total_jobs_by_education
    )

    df["Proportion of jobs with bachelor's degree or advanced degree"] = (
        df[
            "Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree"
        ]
        / total_jobs_by_education
    )

In [75]:
pumas.to_csv(f"puma_census_data_{year}.csv")
migpumas.to_csv(f"migpuma_census_data_{year}.csv")