# convert_tract_wacs_to_puma.ipynb

Similar to the tract to puma, except this does puma to migpuma aggregation.

In [8]:
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.abspath("../../.."))
import lib.io as lio

In [9]:
year = 2018

In [10]:
df = pd.read_csv(f"wac_puma_{year}.csv").set_index("PUMA")
df.index = df.index.astype("str").str.zfill(7)
df.head()

,Total number of jobs,Number of jobs for workers age 29 or younger,Number of jobs for workers age 30 to 54,Number of jobs for workers age 55 or older,Number of jobs with earnings $1250/month or less,Number of jobs with earnings $1251/month to $3333/month,Number of jobs with earnings greater than $3333/month,"Number of jobs in NAICS sector 11 (Agriculture, Forestry, Fishing and Hunting)","Number of jobs in NAICS sector 21 (Mining, Quarrying, and Oil and Gas Extraction)",Number of jobs in NAICS sector 22 (Utilities),...,Number of jobs in NAICS sector 61 (Educational Services),Number of jobs in NAICS sector 62 (Health Care and Social Assistance),"Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)",Number of jobs in NAICS sector 72 (Accommodation and Food Services),Number of jobs in NAICS sector 81 (Other Services [except Public Administration]),Number of jobs in NAICS sector 92 (Public Administration),Number of jobs for workers with Educational Attainment: Less than high school,"Number of jobs for workers with Educational Attainment: High school or equivalent, no college",Number of jobs for workers with Educational Attainment: Some college or Associate degree,Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree
PUMA,,,,,,,,,,,,,,,,,,,,,
0100100,65126,17136,33682,14308,16098,26779,22249,327,187,667,...,5244,8385,547,6459,1295,3035,6271,15596,15924,10199
0100200,55849,12289,30305,13255,11232,16446,28171,589,18,336,...,6750,3403,888,4140,860,3363,4811,12422,13334,12993
0100301,78929,19094,42045,17790,17004,20970,40955,164,74,81,...,4888,4724,1140,8349,1240,747,6405,15300,18471,19659
0100302,73792,18404,39227,16161,19130,26425,28237,13,0,610,...,3284,18803,1187,6280,1788,3981,6420,15549,18625,14794
0100400,38349,9478,20490,8381,8663,17262,12424,339,20,471,...,3249,4185,103,2904,536,1831,4218,10119,9416,5118

In [11]:
puma_migpuma = lio.load_puma_migpuma("../../geometry/equivalencies/puma_migpuma.csv")
puma_migpuma.head()

        State  MIGPUMA
PUMA
0100100    01  0100190
0100200    01  0100290
0100301    01  0100290
0100302    01  0100290
0100400    01  0100400

In [12]:
df["MIGPUMA"] = puma_migpuma.loc[df.index, "MIGPUMA"]
df.head()

,Total number of jobs,Number of jobs for workers age 29 or younger,Number of jobs for workers age 30 to 54,Number of jobs for workers age 55 or older,Number of jobs with earnings $1250/month or less,Number of jobs with earnings $1251/month to $3333/month,Number of jobs with earnings greater than $3333/month,"Number of jobs in NAICS sector 11 (Agriculture, Forestry, Fishing and Hunting)","Number of jobs in NAICS sector 21 (Mining, Quarrying, and Oil and Gas Extraction)",Number of jobs in NAICS sector 22 (Utilities),...,Number of jobs in NAICS sector 62 (Health Care and Social Assistance),"Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)",Number of jobs in NAICS sector 72 (Accommodation and Food Services),Number of jobs in NAICS sector 81 (Other Services [except Public Administration]),Number of jobs in NAICS sector 92 (Public Administration),Number of jobs for workers with Educational Attainment: Less than high school,"Number of jobs for workers with Educational Attainment: High school or equivalent, no college",Number of jobs for workers with Educational Attainment: Some college or Associate degree,Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree,MIGPUMA
PUMA,,,,,,,,,,,,,,,,,,,,,
0100100,65126,17136,33682,14308,16098,26779,22249,327,187,667,...,8385,547,6459,1295,3035,6271,15596,15924,10199,0100190
0100200,55849,12289,30305,13255,11232,16446,28171,589,18,336,...,3403,888,4140,860,3363,4811,12422,13334,12993,0100290
0100301,78929,19094,42045,17790,17004,20970,40955,164,74,81,...,4724,1140,8349,1240,747,6405,15300,18471,19659,0100290
0100302,73792,18404,39227,16161,19130,26425,28237,13,0,610,...,18803,1187,6280,1788,3981,6420,15549,18625,14794,0100290
0100400,38349,9478,20490,8381,8663,17262,12424,339,20,471,...,4185,103,2904,536,1831,4218,10119,9416,5118,0100400

In [13]:
df_MIGPUMA = df.groupby("MIGPUMA").sum()
df_MIGPUMA.head()

,Total number of jobs,Number of jobs for workers age 29 or younger,Number of jobs for workers age 30 to 54,Number of jobs for workers age 55 or older,Number of jobs with earnings $1250/month or less,Number of jobs with earnings $1251/month to $3333/month,Number of jobs with earnings greater than $3333/month,"Number of jobs in NAICS sector 11 (Agriculture, Forestry, Fishing and Hunting)","Number of jobs in NAICS sector 21 (Mining, Quarrying, and Oil and Gas Extraction)",Number of jobs in NAICS sector 22 (Utilities),...,Number of jobs in NAICS sector 61 (Educational Services),Number of jobs in NAICS sector 62 (Health Care and Social Assistance),"Number of jobs in NAICS sector 71 (Arts, Entertainment, and Recreation)",Number of jobs in NAICS sector 72 (Accommodation and Food Services),Number of jobs in NAICS sector 81 (Other Services [except Public Administration]),Number of jobs in NAICS sector 92 (Public Administration),Number of jobs for workers with Educational Attainment: Less than high school,"Number of jobs for workers with Educational Attainment: High school or equivalent, no college",Number of jobs for workers with Educational Attainment: Some college or Associate degree,Number of jobs for workers with Educational Attainment: Bachelor's degree or advanced degree
MIGPUMA,,,,,,,,,,,,,,,,,,,,,
0100190,98779,25260,51315,22204,24429,40764,33586,804,496,1136,...,8442,14392,673,9445,2087,4809,9425,24176,24604,15314
0100290,251113,61138,133922,56053,57381,83406,110326,978,110,1439,...,17880,31247,3529,22888,4706,9503,22517,53389,60427,53642
0100400,38349,9478,20490,8381,8663,17262,12424,339,20,471,...,3249,4185,103,2904,536,1831,4218,10119,9416,5118
0100600,55347,12855,30219,12273,12340,20116,22891,224,68,430,...,3955,6304,283,4922,1059,2021,5588,13943,14067,8894
0100700,37022,9531,19312,8179,8457,16222,12343,483,14,277,...,2931,4713,190,3076,679,1777,3639,9418,9358,5076

In [14]:
df_MIGPUMA.to_csv(f"wac_migpuma_{year}.csv")